<?php
// Comprehensive Database Audit Logging System
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE');
header('Access-Control-Allow-Headers: Content-Type, X-Requested-With');  require_once '../../backend/rbac.php';
require_once '../public/db_connect.php';  // Start session for authentication
session_start();  // Check if user is logged in
if (!isset($_SESSION['user_id'])) {  http_response_code(401);  echo json_encode(['success' => false, 'message' => 'Unauthorized access']);  exit();
}  // Database connection is available as global $pdo from db_connect.php  // Check role-based access control
if (!hasPermission('database_management', 'view')) {  http_response_code(403);  echo json_encode(['success' => false, 'message' => 'Access denied']);  exit();
}  // Get action from request
$action = $_GET['action'] ?? '';  try {  switch ($action) {  case 'log':  handleLogAction($pdo);  break;  case 'view':  handleViewLogs($pdo);  break;  case 'search':  handleSearchLogs($pdo);  break;  case 'export':  handleExportLogs($pdo);  break;  case 'stats':  handleGetStats($pdo);  break;  case 'timeline':  handleGetTimeline($pdo);  break;  default:  http_response_code(400);  echo json_encode(['success' => false, 'message' => 'Invalid action']);  }
} catch (Exception $e) {  http_response_code(500);  echo json_encode(['success' => false, 'message' => 'Server error: ' . $e->getMessage()]);
}  function handleLogAction($pdo) {  $input = json_decode(file_get_contents('php://input'), true);  $action = $input['action'] ?? '';  $details = $input['details'] ?? '';  $table = $input['table'] ?? '';  $recordId = $input['record_id'] ?? null;  $oldValues = $input['old_values'] ?? [];  $newValues = $input['new_values'] ?? [];  if (empty($action) || empty($details)) {  http_response_code(400);  echo json_encode(['success' => false, 'message' => 'Action and details are required']);  return;  }  $auditId = logDatabaseOperation($pdo, [  'user_id' => $_SESSION['user_id'],  'action' => $action,  'details' => $details,  'table' => $table,  'record_id' => $recordId,  'old_values' => $oldValues,  'new_values' => $newValues,  'ip_address' => $_SERVER['REMOTE_ADDR'] ?? 'unknown',  'user_agent' => $_SERVER['HTTP_USER_AGENT'] ?? 'unknown'  ]);  echo json_encode([  'success' => true,  'audit_id' => $auditId,  'message' => 'Action logged successfully'  ]);
}  function handleViewLogs($pdo) {  $page = intval($_GET['page'] ?? 1);  $limit = intval($_GET['limit'] ?? 50);  $offset = ($page - 1) * $limit;  $action = $_GET['action_filter'] ?? '';  $table = $_GET['table_filter'] ?? '';  $userId = $_GET['user_filter'] ?? '';  $dateFrom = $_GET['date_from'] ?? '';  $dateTo = $_GET['date_to'] ?? '';  // Build query  $sql = "SELECT al.*, u.username, u.full_name FROM audit_log al  LEFT JOIN users u ON al.user_id = u.id WHERE 1=1";  $params = [];  if ($action) {  $sql .= " AND al.action LIKE ?";  $params[] = "%$action%";  }  if ($table) {  $sql .= " AND al.table_name = ?";  $params[] = $table;  }  if ($userId) {  $sql .= " AND al.user_id = ?";  $params[] = $userId;  }  if ($dateFrom) {  $sql .= " AND al.created_at >= ?";  $params[] = $dateFrom . ' 00:00:00';  }  if ($dateTo) {  $sql .= " AND al.created_at <= ?";  $params[] = $dateTo . ' 23:59:59';  }  // Get total count  $countSql = str_replace("SELECT al.*, u.username, u.full_name", "SELECT COUNT(*)", $sql);  $countStmt = $pdo->prepare($countSql);  $countStmt->execute($params);  $totalCount = $countStmt->fetchColumn();  // Get logs  $sql .= " ORDER BY al.created_at DESC LIMIT $limit OFFSET $offset";  $stmt = $pdo->prepare($sql);  $stmt->execute($params);  $logs = $stmt->fetchAll(PDO::FETCH_ASSOC);  // Format logs  $formattedLogs = array_map(function($log) {  return [  'id' => $log['id'],  'user_id' => $log['user_id'],  'username' => $log['username'] ?? 'Unknown',  'full_name' => $log['full_name'] ?? 'Unknown User',  'action' => $log['action'],  'details' => $log['details'],  'table_name' => $log['table_name'],  'record_id' => $log['record_id'],  'old_values' => json_decode($log['old_values'] ?? '[]', true),  'new_values' => json_decode($log['new_values'] ?? '[]', true),  'ip_address' => $log['ip_address'],  'user_agent' => $log['user_agent'],  'created_at' => $log['created_at']  ];  }, $logs);  echo json_encode([  'success' => true,  'logs' => $formattedLogs,  'total_count' => $totalCount,  'page' => $page,  'limit' => $limit  ]);
}  function handleSearchLogs($pdo) {  $searchTerm = $_GET['search'] ?? '';  $limit = min(100, intval($_GET['limit'] ?? 50));  if (empty($searchTerm)) {  http_response_code(400);  echo json_encode(['success' => false, 'message' => 'Search term is required']);  return;  }  $sql = "SELECT al.*, u.username, u.full_name FROM audit_log al  LEFT JOIN users u ON al.user_id = u.id  WHERE al.action LIKE ? OR al.details LIKE ? OR u.username LIKE ? OR u.full_name LIKE ?  ORDER BY al.created_at DESC LIMIT $limit";  $searchParam = "%$searchTerm%";  $stmt = $pdo->prepare($sql);  $stmt->execute([$searchParam, $searchParam, $searchParam, $searchParam]);  $logs = $stmt->fetchAll(PDO::FETCH_ASSOC);  // Format logs  $formattedLogs = array_map(function($log) {  return [  'id' => $log['id'],  'user_id' => $log['user_id'],  'username' => $log['username'] ?? 'Unknown',  'full_name' => $log['full_name'] ?? 'Unknown User',  'action' => $log['action'],  'details' => $log['details'],  'table_name' => $log['table_name'],  'record_id' => $log['record_id'],  'created_at' => $log['created_at']  ];  }, $logs);  echo json_encode([  'success' => true,  'logs' => $formattedLogs,  'search_term' => $searchTerm,  'total_count' => count($formattedLogs)  ]);
}  function handleExportLogs($pdo) {  $format = $_GET['format'] ?? 'csv';  $dateFrom = $_GET['date_from'] ?? '';  $dateTo = $_GET['date_to'] ?? '';  // Build query  $sql = "SELECT al.*, u.username, u.full_name FROM audit_log al  LEFT JOIN users u ON al.user_id = u.id WHERE 1=1";  $params = [];  if ($dateFrom) {  $sql .= " AND al.created_at >= ?";  $params[] = $dateFrom . ' 00:00:00';  }  if ($dateTo) {  $sql .= " AND al.created_at <= ?";  $params[] = $dateTo . ' 23:59:59';  }  $sql .= " ORDER BY al.created_at DESC LIMIT 10000"; // Export up to 10,000 records  $stmt = $pdo->prepare($sql);  $stmt->execute($params);  $logs = $stmt->fetchAll(PDO::FETCH_ASSOC);  $filename = 'database_audit_logs_' . date('Y-m-d_H-i-s');  if ($format === 'csv') {  $csv = generateAuditCSV($logs);  header('Content-Type: text/csv');  header('Content-Disposition: attachment; filename="' . $filename . '.csv"');  echo $csv;  } elseif ($format === 'json') {  $json = generateAuditJSON($logs);  header('Content-Type: application/json');  header('Content-Disposition: attachment; filename="' . $filename . '.json"');  echo $json;  } else {  http_response_code(400);  echo json_encode(['success' => false, 'message' => 'Unsupported export format']);  return;  }  // Log export action  logDatabaseOperation($pdo, [  'user_id' => $_SESSION['user_id'],  'action' => 'export_audit_logs',  'details' => "Exported audit logs as $format from $dateFrom to $dateTo",  'ip_address' => $_SERVER['REMOTE_ADDR'] ?? 'unknown',  'user_agent' => $_SERVER['HTTP_USER_AGENT'] ?? 'unknown'  ]);
}  function handleGetStats($pdo) {  $stats = [];  // Total logs  $stmt = $pdo->prepare("SELECT COUNT(*) FROM audit_log");  $stmt->execute();  $stats['total_logs'] = $stmt->fetchColumn();  // Logs today  $stmt = $pdo->prepare("SELECT COUNT(*) FROM audit_log WHERE DATE(created_at) = CURDATE()");  $stmt->execute();  $stats['logs_today'] = $stmt->fetchColumn();  // Logs this week  $stmt = $pdo->prepare("SELECT COUNT(*) FROM audit_log WHERE created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)");  $stmt->execute();  $stats['logs_this_week'] = $stmt->fetchColumn();  // Top actions  $stmt = $pdo->prepare("SELECT action, COUNT(*) as count FROM audit_log GROUP BY action ORDER BY count DESC LIMIT 10");  $stmt->execute();  $stats['top_actions'] = $stmt->fetchAll(PDO::FETCH_ASSOC);  // Top users  $stmt = $pdo->prepare("SELECT u.username, u.full_name, COUNT(*) as count FROM audit_log al  LEFT JOIN users u ON al.user_id = u.id  GROUP BY al.user_id ORDER BY count DESC LIMIT 10");  $stmt->execute();  $stats['top_users'] = $stmt->fetchAll(PDO::FETCH_ASSOC);  // Recent activity  $stmt = $pdo->prepare("SELECT al.*, u.username FROM audit_log al  LEFT JOIN users u ON al.user_id = u.id  ORDER BY al.created_at DESC LIMIT 10");  $stmt->execute();  $stats['recent_activity'] = $stmt->fetchAll(PDO::FETCH_ASSOC);  echo json_encode([  'success' => true,  'stats' => $stats  ]);
}  function handleGetTimeline($pdo) {  $hours = intval($_GET['hours'] ?? 24);  $stmt = $pdo->prepare("SELECT DATE_FORMAT(created_at, '%Y-%m-%d %H:00:00') as hour,  COUNT(*) as count FROM audit_log  WHERE created_at >= DATE_SUB(NOW(), INTERVAL ? HOUR)  GROUP BY DATE_FORMAT(created_at, '%Y-%m-%d %H:00:00')  ORDER BY hour");  $stmt->execute([$hours]);  $timeline = $stmt->fetchAll(PDO::FETCH_ASSOC);  echo json_encode([  'success' => true,  'timeline' => $timeline,  'hours' => $hours  ]);
}  function logDatabaseOperation($pdo, $data) {  try {  // Ensure audit_log table exists with proper structure  $pdo->exec("  CREATE TABLE IF NOT EXISTS audit_log (  id INT AUTO_INCREMENT PRIMARY KEY,  user_id INT,  action VARCHAR(100) NOT NULL,  details TEXT,  table_name VARCHAR(100),  record_id INT,  old_values JSON,  new_values JSON,  ip_address VARCHAR(45),  user_agent TEXT,  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  INDEX idx_user_id (user_id),  INDEX idx_action (action),  INDEX idx_table_name (table_name),  INDEX idx_created_at (created_at)  )  ");  $stmt = $pdo->prepare("  INSERT INTO audit_log (user_id, action, details, table_name, record_id, old_values, new_values, ip_address, user_agent)  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)  ");  $stmt->execute([  $data['user_id'],  $data['action'],  $data['details'],  $data['table'] ?? null,  $data['record_id'] ?? null,  json_encode($data['old_values'] ?? []),  json_encode($data['new_values'] ?? []),  $data['ip_address'],  $data['user_agent']  ]);  return $pdo->lastInsertId();  } catch (Exception $e) {  error_log("Failed to log database operation: " . $e->getMessage());  return null;  }
}  function generateAuditCSV($logs) {  $csv = '';  // Header  $csv .= 'ID,User ID,Username,Full Name,Action,Details,Table,Record ID,IP Address,User Agent,Created At' . "\n";  // Data rows  foreach ($logs as $log) {  $row = [  $log['id'],  $log['user_id'],  $log['username'] ?? '',  $log['full_name'] ?? '',  $log['action'],  str_replace(["\n", "\r", ","], [" ", " ", ";"], $log['details']),  $log['table_name'] ?? '',  $log['record_id'] ?? '',  $log['ip_address'] ?? '',  str_replace(["\n", "\r", ","], [" ", " ", ";"], $log['user_agent'] ?? ''),  $log['created_at']  ];  // Escape and join  $escapedRow = array_map(function($value) {  $value = str_replace('"', '""', $value);  if (strpos($value, ',') !== false || strpos($value, '"') !== false) {  $value = '"' . $value . '"';  }  return $value;  }, $row);  $csv .= implode(',', $escapedRow) . "\n";  }  return $csv;
}  function generateAuditJSON($logs) {  $formattedLogs = array_map(function($log) {  return [  'id' => $log['id'],  'user_id' => $log['user_id'],  'username' => $log['username'] ?? 'Unknown',  'full_name' => $log['full_name'] ?? 'Unknown User',  'action' => $log['action'],  'details' => $log['details'],  'table_name' => $log['table_name'],  'record_id' => $log['record_id'],  'old_values' => json_decode($log['old_values'] ?? '[]', true),  'new_values' => json_decode($log['new_values'] ?? '[]', true),  'ip_address' => $log['ip_address'],  'user_agent' => $log['user_agent'],  'created_at' => $log['created_at']  ];  }, $logs);  return json_encode($formattedLogs, JSON_PRETTY_PRINT);
}
?>
