<?php
// API for PO-Delivery-Inventory System Integration
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, Authorization');  require_once '../config/database_config.php';
require_once '../public/db_connect.php';  // Handle preflight OPTIONS request
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {  exit(0);
}  // Get request method and endpoint
$method = $_SERVER['REQUEST_METHOD'];
$endpoint = $_GET['action'] ?? '';  try {  switch ($endpoint) {  case 'get_po_items':  handleGetPOItems();  break;  case 'get_inventory_status':  handleGetInventoryStatus();  break;  case 'get_low_stock_products':  handleGetLowStockProducts();  break;  case 'get_po_summary':  handleGetPOSummary();  break;  case 'get_delivery_summary':  handleGetDeliverySummary();  break;  case 'auto_suggest_po':  handleAutoSuggestPO();  break;  case 'update_inventory':  handleUpdateInventory();  break;  default:  sendResponse(['error' => 'Invalid endpoint'], 404);  }
} catch (Exception $e) {  sendResponse(['error' => $e->getMessage()], 500);
}  function handleGetPOItems() {  global $pdo;  $po_id = $_GET['po_id'] ?? 0;  if (!$po_id) {  sendResponse(['error' => 'PO ID required'], 400);  }  $stmt = $pdo->prepare("  SELECT pi.*, ip.product_name, ip.category  FROM po_items pi  LEFT JOIN inventory_products ip ON pi.product_id = ip.id  WHERE pi.po_id = ?  ORDER BY ip.product_name  ");  $stmt->execute([$po_id]);  $items = $stmt->fetchAll();  sendResponse(['items' => $items]);
}  function handleGetInventoryStatus() {  global $pdo;  $station_id = $_GET['station_id'] ?? 1;  $stmt = $pdo->prepare("  SELECT  ip.id,  ip.product_name,  ip.category,  ip.unit_cost,  COALESCE(i.quantity_on_hand, 0) as current_stock,  CASE  WHEN COALESCE(i.quantity_on_hand, 0) = 0 THEN 'Out of Stock'  WHEN COALESCE(i.quantity_on_hand, 0) < 10 THEN 'Critical'  WHEN COALESCE(i.quantity_on_hand, 0) < 50 THEN 'Low'  ELSE 'Normal'  END as stock_status  FROM inventory_products ip  LEFT JOIN inventory i ON ip.id = i.product_id AND i.station_id = ?  WHERE ip.category != 'Fuel'  ORDER BY  CASE  WHEN COALESCE(i.quantity_on_hand, 0) = 0 THEN 1  WHEN COALESCE(i.quantity_on_hand, 0) < 10 THEN 2  WHEN COALESCE(i.quantity_on_hand, 0) < 50 THEN 3  ELSE 4  END,  ip.product_name  ");  $stmt->execute([$station_id]);  $products = $stmt->fetchAll();  sendResponse(['products' => $products]);
}  function handleGetLowStockProducts() {  global $pdo;  $station_id = $_GET['station_id'] ?? 1;  $threshold = $_GET['threshold'] ?? 50;  $stmt = $pdo->prepare("  SELECT  ip.id,  ip.product_name,  ip.category,  ip.unit_cost,  COALESCE(i.quantity_on_hand, 0) as current_stock,  CASE  WHEN COALESCE(i.quantity_on_hand, 0) = 0 THEN 100  WHEN COALESCE(i.quantity_on_hand, 0) < 10 THEN 50  WHEN COALESCE(i.quantity_on_hand, 0) < $threshold THEN 25  ELSE 0  END as suggested_order_quantity,  sup.name as preferred_supplier,  sup.id as supplier_id  FROM inventory_products ip  LEFT JOIN inventory i ON ip.id = i.product_id AND i.station_id = ?  LEFT JOIN suppliers sup ON 1=1 LIMIT 1  WHERE ip.category != 'Fuel'  AND (i.quantity_on_hand IS NULL OR i.quantity_on_hand < ?)  ORDER BY i.quantity_on_hand ASC, ip.product_name  LIMIT 10  ");  $stmt->execute([$station_id, $threshold]);  $products = $stmt->fetchAll();  sendResponse(['products' => $products]);
}  function handleGetPOSummary() {  global $pdo;  $station_id = $_GET['station_id'] ?? 1;  $stmt = $pdo->query("  SELECT  COUNT(*) as total_pos,  SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) as pending_pos,  SUM(CASE WHEN status = 'approved' THEN 1 ELSE 0 END) as approved_pos,  SUM(CASE WHEN delivery_status = 'fully_delivered' THEN 1 ELSE 0 END) as delivered_pos,  SUM(CASE WHEN delivery_status = 'partially_delivered' THEN 1 ELSE 0 END) as partially_delivered_pos,  COALESCE(SUM(total_amount), 0) as total_value  FROM v_po_delivery_summary  WHERE station_id = $station_id  ");  $summary = $stmt->fetch();  // Get recent POs  $stmt = $pdo->prepare("  SELECT po_number, supplier_name, status, delivery_status, created_at, total_amount  FROM v_po_delivery_summary  WHERE station_id = ?  ORDER BY created_at DESC  LIMIT 5  ");  $stmt->execute([$station_id]);  $recent_pos = $stmt->fetchAll();  sendResponse([  'summary' => $summary,  'recent_pos' => $recent_pos  ]);
}  function handleGetDeliverySummary() {  global $pdo;  $station_id = $_GET['station_id'] ?? 1;  $stmt = $pdo->query("  SELECT  COUNT(*) as total_deliveries,  SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) as pending_deliveries,  SUM(CASE WHEN status = 'confirmed' THEN 1 ELSE 0 END) as confirmed_deliveries,  SUM(CASE WHEN status = 'discrepancy' THEN 1 ELSE 0 END) as discrepancy_deliveries,  COALESCE(SUM(total_amount), 0) as total_value  FROM merchandise_deliveries  WHERE station_id = $station_id  ");  $summary = $stmt->fetch();  // Get recent deliveries  $stmt = $pdo->prepare("  SELECT md.delivery_number, po.po_number, s.name as supplier_name,  md.status, md.delivery_date, md.total_amount  FROM merchandise_deliveries md  LEFT JOIN purchase_orders po ON md.po_id = po.id  LEFT JOIN suppliers s ON md.supplier_id = s.id  WHERE md.station_id = ?  ORDER BY md.delivery_date DESC  LIMIT 5  ");  $stmt->execute([$station_id]);  $recent_deliveries = $stmt->fetchAll();  sendResponse([  'summary' => $summary,  'recent_deliveries' => $recent_deliveries  ]);
}  function handleAutoSuggestPO() {  global $pdo;  $station_id = $_GET['station_id'] ?? 1;  // Get low stock products  $stmt = $pdo->prepare("  SELECT  ip.id as product_id,  ip.product_name,  ip.category,  ip.unit_cost,  COALESCE(i.quantity_on_hand, 0) as current_stock,  CASE  WHEN COALESCE(i.quantity_on_hand, 0) = 0 THEN 100  WHEN COALESCE(i.quantity_on_hand, 0) < 10 THEN 50  WHEN COALESCE(i.quantity_on_hand, 0) < 50 THEN 25  ELSE 0  END as suggested_quantity,  sup.id as supplier_id,  sup.name as supplier_name  FROM inventory_products ip  LEFT JOIN inventory i ON ip.id = i.product_id AND i.station_id = ?  LEFT JOIN suppliers sup ON 1=1 LIMIT 1  WHERE ip.category != 'Fuel'  AND (i.quantity_on_hand IS NULL OR i.quantity_on_hand < 50)  ORDER BY i.quantity_on_hand ASC  LIMIT 10  ");  $stmt->execute([$station_id]);  $products = $stmt->fetchAll();  if (empty($products)) {  sendResponse(['message' => 'No low stock products found', 'suggested_po' => null]);  }  // Group by supplier for PO suggestions  $supplier_groups = [];  foreach ($products as $product) {  $supplier_id = $product['supplier_id'];  if (!isset($supplier_groups[$supplier_id])) {  $supplier_groups[$supplier_id] = [  'supplier_id' => $supplier_id,  'supplier_name' => $product['supplier_name'],  'products' => [],  'total_quantity' => 0,  'total_amount' => 0  ];  }  $supplier_groups[$supplier_id]['products'][] = $product;  $supplier_groups[$supplier_id]['total_quantity'] += $product['suggested_quantity'];  $supplier_groups[$supplier_id]['total_amount'] += $product['suggested_quantity'] * $product['unit_cost'];  }  sendResponse([  'low_stock_products' => $products,  'suggested_po_groups' => array_values($supplier_groups)  ]);
}  function handleUpdateInventory() {  global $pdo;  if ($_SERVER['REQUEST_METHOD'] !== 'POST') {  sendResponse(['error' => 'POST method required'], 405);  }  $data = json_decode(file_get_contents('php://input'), true);  $station_id = $data['station_id'] ?? 1;  $product_id = $data['product_id'] ?? 0;  $quantity = $data['quantity'] ?? 0;  $operation = $data['operation'] ?? 'add'; // add, subtract, set  if (!$product_id) {  sendResponse(['error' => 'Product ID required'], 400);  }  $pdo->beginTransaction();  try {  // Check if inventory record exists  $stmt = $pdo->prepare("SELECT id, quantity_on_hand FROM inventory WHERE station_id = ? AND product_id = ?");  $stmt->execute([$station_id, $product_id]);  $inventory = $stmt->fetch();  if ($inventory) {  // Update existing inventory  $new_quantity = $inventory['quantity_on_hand'];  switch ($operation) {  case 'add':  $new_quantity += $quantity;  break;  case 'subtract':  $new_quantity -= $quantity;  break;  case 'set':  $new_quantity = $quantity;  break;  }  if ($new_quantity < 0) {  throw new Exception('Insufficient inventory');  }  $stmt = $pdo->prepare("  UPDATE inventory  SET quantity_on_hand = ?, last_updated = NOW()  WHERE id = ?  ");  $stmt->execute([$new_quantity, $inventory['id']]);  } else {  // Create new inventory record  if ($operation === 'subtract') {  throw new Exception('Cannot subtract from non-existent inventory');  }  $new_quantity = ($operation === 'set') ? $quantity : $quantity;  $stmt = $pdo->prepare("  INSERT INTO inventory (station_id, product_id, quantity_on_hand, last_updated)  VALUES (?, ?, ?, NOW())  ");  $stmt->execute([$station_id, $product_id, $new_quantity]);  }  $pdo->commit();  sendResponse([  'success' => true,  'new_quantity' => $new_quantity,  'message' => 'Inventory updated successfully'  ]);  } catch (Exception $e) {  $pdo->rollback();  throw $e;  }
}  function sendResponse($data, $statusCode = 200) {  http_response_code($statusCode);  echo json_encode($data);  exit;
}
?>
