<?php
/**  * Database Helper Functions  * Provides utility functions for common database operations  * that need to handle schema variations  */  /**  * Get SQL fragment for selecting user name from users table  * Handles both 'name' column and 'first_name'/'last_name' columns  *  * @param string $alias The table alias (e.g., 'u', 'staff', 'validator')  * @param string $result_alias The result column alias (e.g., 'staff_name', 'user_name')  * @return string SQL fragment for COALESCE statement  *  * @example  * $sql = "SELECT ft.*, " . get_user_name_sql('u', 'staff_name') . "  *  FROM fuel_transactions ft  *  LEFT JOIN users u ON ft.staff_id = u.id";  */
function get_user_name_sql($alias, $result_alias = 'user_name') {  return "COALESCE(  NULLIF(TRIM({$alias}.name), ''),  NULLIF(CONCAT(TRIM({$alias}.first_name), ' ', TRIM({$alias}.last_name)), ' '),  {$alias}.username,  'Unknown'  ) as {$result_alias}";
}  /**  * Get user's full name from user record  * Handles both 'name' field and 'first_name'/'last_name' fields  *  * @param array $user User record from database  * @return string User's full name or username as fallback  *  * @example  * $stmt = $pdo->prepare("SELECT * FROM users WHERE user_id = ?");  * $stmt->execute([$user_id]);  * $user = $stmt->fetch(PDO::FETCH_ASSOC);  * echo get_user_display_name($user);  */
function get_user_display_name($user) {  if (empty($user)) {  return 'Unknown';  }  // Try 'name' field first  if (!empty($user['name'])) {  return trim($user['name']);  }  // Try concatenating first_name and last_name  if (!empty($user['first_name']) || !empty($user['last_name'])) {  $fname = trim($user['first_name'] ?? '');  $lname = trim($user['last_name'] ?? '');  $full_name = trim("$fname $lname");  if (!empty($full_name)) {  return $full_name;  }  }  // Fall back to username  if (!empty($user['username'])) {  return trim($user['username']);  }  return 'Unknown';
}  /**  * Get SQL for joining users table with name selection  *  * @param string $join_type JOIN type (LEFT, INNER, RIGHT)  * @param string $alias Table alias for users table  * @param string $on_condition JOIN condition (e.g., "ft.staff_id = u.id")  * @param string $name_alias Result column alias  * @return string Complete JOIN clause with name selection  *  * @example  * $sql = "SELECT ft.* " . get_user_join_with_name('LEFT', 'staff', 'ft.staff_id = staff.id', 'staff_name') . "  *  FROM fuel_transactions ft";  */
function get_user_join_with_name($join_type, $alias, $on_condition, $name_alias = 'user_name') {  $name_sql = get_user_name_sql($alias, $name_alias);  return ", {$name_sql}\n  {$join_type} JOIN users {$alias} ON {$on_condition}";
}  /**  * Check if users table has 'name' column or 'first_name'/'last_name' columns  * Caches result to avoid repeated queries  *  * @param PDO $pdo Database connection  * @return array ['has_name' => bool, 'has_first_last' => bool]  */
function check_users_table_schema($pdo) {  static $cache = null;  if ($cache !== null) {  return $cache;  }  try {  $stmt = $pdo->query("SHOW COLUMNS FROM users");  $columns = $stmt->fetchAll(PDO::FETCH_COLUMN);  $cache = [  'has_name' => in_array('name', $columns),  'has_first_last' => in_array('first_name', $columns) && in_array('last_name', $columns)  ];  return $cache;  } catch (Exception $e) {  // If query fails, assume both schemas for safety  return ['has_name' => true, 'has_first_last' => true];  }
}  /**  * Get optimized user name SQL based on actual table schema  * Only includes COALESCE options that exist in the database  *  * @param PDO $pdo Database connection  * @param string $alias Table alias  * @param string $result_alias Result column alias  * @return string Optimized SQL fragment  */
function get_optimized_user_name_sql($pdo, $alias, $result_alias = 'user_name') {  $schema = check_users_table_schema($pdo);  $options = [];  if ($schema['has_name']) {  $options[] = "NULLIF(TRIM({$alias}.name), '')";  }  if ($schema['has_first_last']) {  $options[] = "NULLIF(CONCAT(TRIM({$alias}.first_name), ' ', TRIM({$alias}.last_name)), ' ')";  }  $options[] = "{$alias}.username";  $options[] = "'Unknown'";  return "COALESCE(" . implode(", ", $options) . ") as {$result_alias}";
}
