<?php
// Soft Deleted Records Tab - Restore or permanently purge functionality
global $pdo, $config;
?>  <div class="soft-deleted-container">  <div class="soft-deleted-header">  <p><i class="fas fa-info-circle"></i> View and manage soft-deleted records. You can restore records to active status or permanently purge them from the system.</p>  </div>  <div class="soft-delete-tables">  <?php foreach ($config['soft_delete_tables'] as $table): ?>  <div class="soft-delete-card">  <h4>  <i class="fas fa-table"></i>  <?php echo htmlspecialchars($table['display_name']); ?>  </h4>  <div class="table-info">  <p><strong>Table:</strong> <?php echo htmlspecialchars($table['table_name']); ?></p>  <p><strong>Soft Delete Column:</strong> <?php echo htmlspecialchars($table['soft_delete_column']); ?></p>  <p><strong>Inactive Value:</strong> <?php echo htmlspecialchars($table['inactive_value']); ?></p>  </div>  <div class="record-stats" id="stats-<?php echo $table['table_key']; ?>">  <p><i class="fas fa-spinner fa-spin"></i> Loading record count...</p>  </div>  <div class="soft-delete-actions">  <button class="btn-view" onclick="viewSoftDeletedRecords('<?php echo $table['table_key']; ?>', '<?php echo htmlspecialchars($table['table_name']); ?>')">  <i class="fas fa-eye"></i> View Records  </button>  <?php if ($table['restore_enabled']): ?>  <button class="btn-restore" onclick="restoreRecords('<?php echo $table['table_key']; ?>', '<?php echo htmlspecialchars($table['table_name']); ?>')">  <i class="fas fa-undo"></i> Restore  </button>  <?php endif; ?>  <?php if ($table['purge_enabled']): ?>  <button class="btn-purge" onclick="purgeRecords('<?php echo $table['table_key']; ?>', '<?php echo htmlspecialchars($table['table_name']); ?>')">  <i class="fas fa-trash"></i> Purge  </button>  <?php endif; ?>  </div>  </div>  <?php endforeach; ?>  </div>
</div>  <!-- Records Modal -->
<div id="recordsModal" class="modal" style="display: none;">  <div class="modal-content large">  <div class="modal-header">  <h3><i class="fas fa-list"></i> Soft Deleted Records</h3>  <button class="modal-close" onclick="closeRecordsModal()">&times;</button>  </div>  <div class="modal-body">  <div id="recordsContent"></div>  </div>  </div>
</div>  <!-- Restore Confirmation Modal -->
<div id="restoreModal" class="modal" style="display: none;">  <div class="modal-content">  <div class="modal-header">  <h3><i class="fas fa-undo"></i> Restore Records</h3>  <button class="modal-close" onclick="closeRestoreModal()">&times;</button>  </div>  <div class="modal-body">  <p>Select records to restore:</p>  <div id="restoreContent"></div>  <div class="modal-actions">  <button class="btn-restore" onclick="confirmRestore()">  <i class="fas fa-check"></i> Restore Selected  </button>  <button class="btn-cancel" onclick="closeRestoreModal()">  <i class="fas fa-times"></i> Cancel  </button>  </div>  </div>  </div>
</div>  <!-- Purge Confirmation Modal -->
<div id="purgeModal" class="modal" style="display: none;">  <div class="modal-content">  <div class="modal-header danger">  <h3><i class="fas fa-exclamation-triangle"></i> Purge Records</h3>  <button class="modal-close" onclick="closePurgeModal()">&times;</button>  </div>  <div class="modal-body">  <div class="alert alert-danger">  <strong>WARNING:</strong> This action will permanently delete records and cannot be undone!  </div>  <p>Select records to permanently purge:</p>  <div id="purgeContent"></div>  <div class="modal-actions">  <button class="btn-purge" onclick="confirmPurge()">  <i class="fas fa-trash"></i> Permanently Purge  </button>  <button class="btn-cancel" onclick="closePurgeModal()">  <i class="fas fa-times"></i> Cancel  </button>  </div>  </div>  </div>
</div>  <style>
.soft-deleted-header {  background: #f8f9fa;  padding: 20px;  border-radius: 10px;  margin-bottom: 30px;  border-left: 4px solid #667eea;
}  .table-info {  background: #e9ecef;  padding: 15px;  border-radius: 5px;  margin: 15px 0;
}  .table-info p {  margin: 5px 0;  font-size: 0.9rem;
}  .record-stats {  background: #d1ecf1;  border: 1px solid #bee5eb;  padding: 15px;  border-radius: 5px;  margin: 15px 0;  color: #0c5460;
}  .record-stats p {  margin: 0;
}  .modal-content.large {  max-width: 90%;  margin: 50px auto;
}  .modal-header.danger {  background: linear-gradient(135deg, #dc3545 0%, #c82333 100%);
}  .modal-actions {  display: flex;  gap: 10px;  justify-content: flex-end;  margin-top: 20px;  padding-top: 20px;  border-top: 1px solid #e9ecef;
}  .btn-cancel {  background: #6c757d;  color: white;  border: none;  padding: 10px 20px;  border-radius: 5px;  cursor: pointer;
}  .records-table {  width: 100%;  border-collapse: collapse;  margin-top: 15px;
}  .records-table th,
.records-table td {  padding: 10px;  text-align: left;  border-bottom: 1px solid #e9ecef;
}  .records-table th {  background: #f8f9fa;  font-weight: 600;
}  .records-table tr:hover {  background: #f8f9fa;
}  .checkbox-cell {  width: 50px;
}  .record-actions {  display: flex;  gap: 5px;
}  .btn-small {  padding: 4px 8px;  font-size: 0.8rem;  border: none;  border-radius: 3px;  cursor: pointer;
}  .btn-restore-single {  background: #28a745;  color: white;
}  .btn-purge-single {  background: #dc3545;  color: white;
}  .pagination {  display: flex;  justify-content: center;  gap: 5px;  margin-top: 20px;
}  .pagination button {  padding: 5px 10px;  border: 1px solid #e9ecef;  background: white;  cursor: pointer;
}  .pagination button.active {  background: #667eea;  color: white;
}  .pagination button:hover {  background: #f8f9fa;
}
</style>  <script>
// Load record statistics for each table
document.addEventListener('DOMContentLoaded', function() {  <?php foreach ($config['soft_delete_tables'] as $table): ?>  loadRecordStats('<?php echo $table['table_key']; ?>');  <?php endforeach; ?>
});  function loadRecordStats(tableKey) {  fetch(`../backend/api/soft_deleted_records.php?action=stats&table=${tableKey}`)  .then(response => response.json())  .then(data => {  const statsDiv = document.getElementById(`stats-${tableKey}`);  if (data.success) {  statsDiv.innerHTML = `  <p><strong>Total Soft Deleted Records:</strong> ${data.count}</p>  <p><strong>Last Modified:</strong> ${data.last_modified || 'Unknown'}</p>  `;  } else {  statsDiv.innerHTML = `<p><i class="fas fa-exclamation-triangle"></i> Error loading stats</p>`;  }  })  .catch(error => {  console.error('Error loading stats:', error);  document.getElementById(`stats-${tableKey}`).innerHTML = `<p><i class="fas fa-exclamation-triangle"></i> Connection error</p>`;  });
}  function viewSoftDeletedRecords(tableKey, tableName) {  fetch(`../backend/api/soft_deleted_records.php?action=view&table=${tableKey}`)  .then(response => response.json())  .then(data => {  if (data.success) {  displayRecords(tableName, data.records, data.columns);  document.getElementById('recordsModal').style.display = 'block';  } else {  alert('Error loading records: ' + data.message);  }  })  .catch(error => {  console.error('Error:', error);  alert('Error loading records');  });
}  function displayRecords(tableName, records, columns) {  const content = document.getElementById('recordsContent');  if (records.length === 0) {  content.innerHTML = '<p>No soft deleted records found.</p>';  return;  }  let html = `  <h4>${tableName} - Soft Deleted Records</h4>  <div class="table-responsive">  <table class="records-table">  <thead>  <tr>  <th class="checkbox-cell">  <input type="checkbox" id="selectAll" onchange="toggleAllRecords()">  </th>  `;  columns.forEach(col => {  html += `<th>${col}</th>`;  });  html += `  <th>Actions</th>  </tr>  </thead>  <tbody>  `;  records.forEach((record, index) => {  html += `  <tr>  <td class="checkbox-cell">  <input type="checkbox" class="record-checkbox" value="${record.id}" data-index="${index}">  </td>  `;  columns.forEach(col => {  const value = record[col] || '';  html += `<td>${value}</td>`;  });  html += `  <td class="record-actions">  <button class="btn-small btn-restore-single" onclick="restoreSingleRecord('${tableName}', ${record.id})">  <i class="fas fa-undo"></i>  </button>  <button class="btn-small btn-purge-single" onclick="purgeSingleRecord('${tableName}', ${record.id})">  <i class="fas fa-trash"></i>  </button>  </td>  </tr>  `;  });  html += `  </tbody>  </table>  </div>  `;  content.innerHTML = html;
}  function toggleAllRecords() {  const selectAll = document.getElementById('selectAll');  const checkboxes = document.querySelectorAll('.record-checkbox');  checkboxes.forEach(checkbox => {  checkbox.checked = selectAll.checked;  });
}  function restoreRecords(tableKey, tableName) {  fetch(`../backend/api/soft_deleted_records.php?action=view&table=${tableKey}`)  .then(response => response.json())  .then(data => {  if (data.success) {  displayRestoreOptions(tableName, data.records, data.columns, tableKey);  document.getElementById('restoreModal').style.display = 'block';  } else {  alert('Error loading records for restore: ' + data.message);  }  })  .catch(error => {  console.error('Error:', error);  alert('Error loading records for restore');  });
}  function displayRestoreOptions(tableName, records, columns, tableKey) {  const content = document.getElementById('restoreContent');  if (records.length === 0) {  content.innerHTML = '<p>No records available for restore.</p>';  return;  }  let html = `  <input type="hidden" id="restoreTableKey" value="${tableKey}">  <div class="table-responsive">  <table class="records-table">  <thead>  <tr>  <th class="checkbox-cell">  <input type="checkbox" id="restoreSelectAll" onchange="toggleRestoreAllRecords()">  </th>  `;  columns.forEach(col => {  html += `<th>${col}</th>`;  });  html += `  </tr>  </thead>  <tbody>  `;  records.forEach(record => {  html += `  <tr>  <td class="checkbox-cell">  <input type="checkbox" class="restore-checkbox" value="${record.id}">  </td>  `;  columns.forEach(col => {  const value = record[col] || '';  html += `<td>${value}</td>`;  });  html += `</tr>`;  });  html += `  </tbody>  </table>  </div>  `;  content.innerHTML = html;
}  function toggleRestoreAllRecords() {  const selectAll = document.getElementById('restoreSelectAll');  const checkboxes = document.querySelectorAll('.restore-checkbox');  checkboxes.forEach(checkbox => {  checkbox.checked = selectAll.checked;  });
}  function confirmRestore() {  const tableKey = document.getElementById('restoreTableKey').value;  const checkboxes = document.querySelectorAll('.restore-checkbox:checked');  const recordIds = Array.from(checkboxes).map(cb => cb.value);  if (recordIds.length === 0) {  alert('Please select at least one record to restore.');  return;  }  if (confirm(`Are you sure you want to restore ${recordIds.length} record(s)?`)) {  fetch('../backend/api/soft_deleted_records.php', {  method: 'POST',  headers: {  'Content-Type': 'application/json',  'X-Requested-With': 'XMLHttpRequest'  },  body: JSON.stringify({  action: 'restore',  table: tableKey,  record_ids: recordIds  })  })  .then(response => response.json())  .then(data => {  if (data.success) {  alert(`Successfully restored ${data.restored_count} record(s).`);  closeRestoreModal();  loadRecordStats(tableKey);  } else {  alert('Error restoring records: ' + data.message);  }  })  .catch(error => {  console.error('Error:', error);  alert('Error restoring records');  });  }
}  function purgeRecords(tableKey, tableName) {  fetch(`../backend/api/soft_deleted_records.php?action=view&table=${tableKey}`)  .then(response => response.json())  .then(data => {  if (data.success) {  displayPurgeOptions(tableName, data.records, data.columns, tableKey);  document.getElementById('purgeModal').style.display = 'block';  } else {  alert('Error loading records for purge: ' + data.message);  }  })  .catch(error => {  console.error('Error:', error);  alert('Error loading records for purge');  });
}  function displayPurgeOptions(tableName, records, columns, tableKey) {  const content = document.getElementById('purgeContent');  if (records.length === 0) {  content.innerHTML = '<p>No records available for purge.</p>';  return;  }  let html = `  <input type="hidden" id="purgeTableKey" value="${tableKey}">  <div class="table-responsive">  <table class="records-table">  <thead>  <tr>  <th class="checkbox-cell">  <input type="checkbox" id="purgeSelectAll" onchange="togglePurgeAllRecords()">  </th>  `;  columns.forEach(col => {  html += `<th>${col}</th>`;  });  html += `  </tr>  </thead>  <tbody>  `;  records.forEach(record => {  html += `  <tr>  <td class="checkbox-cell">  <input type="checkbox" class="purge-checkbox" value="${record.id}">  </td>  `;  columns.forEach(col => {  const value = record[col] || '';  html += `<td>${value}</td>`;  });  html += `</tr>`;  });  html += `  </tbody>  </table>  </div>  `;  content.innerHTML = html;
}  function togglePurgeAllRecords() {  const selectAll = document.getElementById('purgeSelectAll');  const checkboxes = document.querySelectorAll('.purge-checkbox');  checkboxes.forEach(checkbox => {  checkbox.checked = selectAll.checked;  });
}  function confirmPurge() {  const tableKey = document.getElementById('purgeTableKey').value;  const checkboxes = document.querySelectorAll('.purge-checkbox:checked');  const recordIds = Array.from(checkboxes).map(cb => cb.value);  if (recordIds.length === 0) {  alert('Please select at least one record to purge.');  return;  }  const confirmMessage = `DANGER: You are about to permanently delete ${recordIds.length} record(s).\n\nThis action cannot be undone and will permanently remove all selected data from the system.\n\nAre you absolutely sure you want to continue?`;  if (confirm(confirmMessage)) {  fetch('../backend/api/soft_deleted_records.php', {  method: 'POST',  headers: {  'Content-Type': 'application/json',  'X-Requested-With': 'XMLHttpRequest'  },  body: JSON.stringify({  action: 'purge',  table: tableKey,  record_ids: recordIds  })  })  .then(response => response.json())  .then(data => {  if (data.success) {  alert(`Successfully purged ${data.purged_count} record(s).`);  closePurgeModal();  loadRecordStats(tableKey);  } else {  alert('Error purging records: ' + data.message);  }  })  .catch(error => {  console.error('Error:', error);  alert('Error purging records');  });  }
}  function restoreSingleRecord(tableName, recordId) {  if (confirm(`Are you sure you want to restore this record?`)) {  // Implementation for single record restore  console.log('Restore single record:', tableName, recordId);  }
}  function purgeSingleRecord(tableName, recordId) {  const confirmMessage = `DANGER: You are about to permanently delete this record.\n\nThis action cannot be undone.\n\nAre you absolutely sure you want to continue?`;  if (confirm(confirmMessage)) {  // Implementation for single record purge  console.log('Purge single record:', tableName, recordId);  }
}  function closeRecordsModal() {  document.getElementById('recordsModal').style.display = 'none';
}  function closeRestoreModal() {  document.getElementById('restoreModal').style.display = 'none';
}  function closePurgeModal() {  document.getElementById('purgeModal').style.display = 'none';
}
</script>
