<?php
/**
 * Official Employee Master List & Document Status Exporter
 * Petron Station Management System
 */
require_once __DIR__ . '/../backend/lib.php';
require_once __DIR__ . '/db_connect.php';
require_once __DIR__ . '/../vendor/autoload.php';

require_login();

$me = current_user();
$my_role = role_key($me['role'] ?? 'staff');
$my_station_id = user_station_id();

// Access Control: Only Manager, Admin, and Superadmin can export employee list
if (!in_array($my_role, ['manager', 'admin', 'superadmin'], true)) {
    http_response_code(403);
    exit('Unauthorized access.');
}

$format = $_GET['format'] ?? 'excel';
$today = date('Y-m-d');
$now_formatted = date('F j, Y h:i A');

// Fetch Station Name
$station_name = 'Petron Carmen';
if ($my_station_id) {
    $stn_stmt = $pdo->prepare("SELECT name FROM stations WHERE id = ?");
    $stn_stmt->execute([$my_station_id]);
    $stn_row = $stn_stmt->fetch(PDO::FETCH_ASSOC);
    if ($stn_row && !empty($stn_row['name'])) {
        $station_name = $stn_row['name'];
    }
}

// Fetch Employees based on station authorization
$user_cols_sql = "
    u.id,
    u.employee_id,
    u.first_name,
    u.last_name,
    CONCAT(COALESCE(u.first_name,''), ' ', COALESCE(u.last_name,'')) AS full_name,
    u.username,
    u.role,
    u.email,
    u.phone_number,
    u.status,
    u.created_at,
    u.updated_at,
    s.name AS station_name
";

if ($my_role === 'superadmin') {
    $stmt = $pdo->query("
        SELECT {$user_cols_sql}
        FROM users u
        LEFT JOIN stations s ON u.station_id = s.id
        ORDER BY u.created_at ASC
    ");
    $employees = $stmt->fetchAll(PDO::FETCH_ASSOC);
} else {
    $stmt = $pdo->prepare("
        SELECT {$user_cols_sql}
        FROM users u
        LEFT JOIN stations s ON u.station_id = s.id
        WHERE u.station_id = ?
        ORDER BY u.role, u.username ASC
    ");
    $stmt->execute([$my_station_id]);
    $employees = $stmt->fetchAll(PDO::FETCH_ASSOC);
}

$record_count = count($employees);
$clean_station_name = preg_replace('/[^a-zA-Z0-9_\-]/', '_', str_replace(' ', '_', $station_name));

// Log Audit Trail
try {
    $audit_format_label = strtoupper(str_replace('_', ' ', $format));
    log_activity(
        $pdo,
        $me['id'],
        'Exported Employee List',
        "Exported $record_count employee records (Format: $audit_format_label, Station: $station_name)"
    );
} catch (Exception $e) { /* ignore */ }

// Helper function for normalized roles
function get_export_role_label($role) {
    $r = strtolower(trim($role));
    if ($r === 'superadmin') return 'Super Admin';
    if ($r === 'admin') return 'Admin/Owner';
    if ($r === 'manager') return 'Manager';
    if ($r === 'staff') return 'Staff';
    return ucfirst($r);
}

// ── 1. EXCEL EXPORT (EMPLOYEE MASTER LIST) ──────────────────────────────────
if ($format === 'excel') {
    $filename = "{$clean_station_name}_Employee_List_{$today}.csv";
    
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    
    $output = fopen('php://output', 'w');
    // UTF-8 BOM for Excel compatibility
    fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));
    
    // Header Info Rows
    fputcsv($output, ['PETRON STATION MANAGEMENT SYSTEM']);
    fputcsv($output, ['EMPLOYEE MASTER LIST']);
    fputcsv($output, ['Station/Branch:', $station_name]);
    fputcsv($output, ['Generated By:', trim(($me['first_name'] ?? '') . ' ' . ($me['last_name'] ?? '')) ?: $me['username']]);
    fputcsv($output, ['Generated Date:', $now_formatted]);
    fputcsv($output, ['Total Employees:', $record_count]);
    fputcsv($output, []); // Empty row gap
    
    // Column Headers
    fputcsv($output, [
        'Employee ID',
        'Full Name',
        'Username',
        'Role',
        'Station/Branch',
        'Account Status',
        'Date Created',
        'Last Login'
    ]);
    
    foreach ($employees as $emp) {
        $emp_id    = $emp['employee_id'] ?: ('EMP-' . str_pad($emp['id'], 4, '0', STR_PAD_LEFT));
        $name      = trim($emp['full_name']) ?: $emp['username'];
        $role_name = get_export_role_label($emp['role']);
        $stn_name  = $emp['station_name'] ?: $station_name;
        $status    = ucfirst(strtolower(trim($emp['status'] ?: 'Active')));
        $created   = $emp['created_at'] ? date('M j, Y', strtotime($emp['created_at'])) : '—';
        $last_login= $emp['updated_at'] ? date('M j, Y h:i A', strtotime($emp['updated_at'])) : '—';
        
        fputcsv($output, [
            $emp_id,
            $name,
            '@' . $emp['username'],
            $role_name,
            $stn_name,
            $status,
            $created,
            $last_login
        ]);
    }
    
    fclose($output);
    exit;
}

// ── 2. EXCEL EXPORT (EMPLOYEE + DOCUMENT STATUS) ───────────────────────────
if ($format === 'excel_docs') {
    $filename = "{$clean_station_name}_Employee_Document_Status_{$today}.csv";
    
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    
    $output = fopen('php://output', 'w');
    fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));
    
    fputcsv($output, ['PETRON STATION MANAGEMENT SYSTEM']);
    fputcsv($output, ['EMPLOYEE DOCUMENT STATUS REPORT']);
    fputcsv($output, ['Station/Branch:', $station_name]);
    fputcsv($output, ['Generated By:', trim(($me['first_name'] ?? '') . ' ' . ($me['last_name'] ?? '')) ?: $me['username']]);
    fputcsv($output, ['Generated Date:', $now_formatted]);
    fputcsv($output, []);
    
    fputcsv($output, [
        'Employee ID',
        'Employee Name',
        'Role',
        'SSS Status',
        'PhilHealth Status',
        'Pag-IBIG Status',
        'TIN Status',
        'Valid ID Status',
        'Employment Docs Status',
        'Other Docs Status'
    ]);
    
    // Fetch all document records
    $docs_map = [];
    try {
        $docs_query = $pdo->query("SELECT user_id, doc_type, status FROM employee_documents");
        while ($d = $docs_query->fetch(PDO::FETCH_ASSOC)) {
            $docs_map[$d['user_id']][$d['doc_type']] = $d['status'];
        }
    } catch (Exception $e) {}
    
    foreach ($employees as $emp) {
        $uid       = $emp['id'];
        $emp_id    = $emp['employee_id'] ?: ('EMP-' . str_pad($uid, 4, '0', STR_PAD_LEFT));
        $name      = trim($emp['full_name']) ?: $emp['username'];
        $role_name = get_export_role_label($emp['role']);
        
        $sss        = $docs_map[$uid]['SSS'] ?? 'Complete';
        $philhealth = $docs_map[$uid]['PhilHealth'] ?? 'Complete';
        $pagibig    = $docs_map[$uid]['Pag-IBIG'] ?? 'Complete';
        $tin        = $docs_map[$uid]['TIN'] ?? 'Complete';
        $valid_id   = $docs_map[$uid]['Valid ID'] ?? 'Complete';
        $employment = $docs_map[$uid]['Employment'] ?? 'Complete';
        $other      = $docs_map[$uid]['Other'] ?? 'Complete';
        
        fputcsv($output, [
            $emp_id,
            $name,
            $role_name,
            $sss,
            $philhealth,
            $pagibig,
            $tin,
            $valid_id,
            $employment,
            $other
        ]);
    }
    
    fclose($output);
    exit;
}

// ── 3. PDF EXPORT (EMPLOYEE MASTER LIST OR DOCUMENT STATUS) ─────────────────
$is_docs_pdf = ($format === 'pdf_docs');
$title = $is_docs_pdf ? 'EMPLOYEE DOCUMENT STATUS REPORT' : 'EMPLOYEE MASTER LIST';
$admin_name = trim(($me['first_name'] ?? '') . ' ' . ($me['last_name'] ?? '')) ?: $me['username'];

// Fetch document status map if PDF docs report
$docs_map = [];
if ($is_docs_pdf) {
    try {
        $docs_query = $pdo->query("SELECT user_id, doc_type, status FROM employee_documents");
        while ($d = $docs_query->fetch(PDO::FETCH_ASSOC)) {
            $docs_map[$d['user_id']][$d['doc_type']] = $d['status'];
        }
    } catch (Exception $e) {}
}

ob_start();
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    body { font-family: 'Helvetica', 'Arial', sans-serif; color: #1e293b; font-size: 11px; margin: 0; padding: 0; }
    .header-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; border-bottom: 2px solid #002F70; padding-bottom: 10px; }
    .header-logo { font-size: 18px; font-weight: bold; color: #002F70; text-transform: uppercase; letter-spacing: 0.5px; }
    .header-title { font-size: 14px; font-weight: bold; color: #334155; margin-top: 4px; text-transform: uppercase; }
    .meta-table { width: 100%; margin-bottom: 15px; background: #f8fafc; padding: 10px 14px; border-radius: 6px; border: 1px solid #e2e8f0; }
    .meta-table td { padding: 4px 8px; font-size: 11px; }
    .meta-lbl { font-weight: bold; color: #002F70; width: 120px; }
    .data-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    .data-table th { background: #002F70; color: #ffffff; padding: 8px 10px; font-size: 10px; text-transform: uppercase; font-weight: bold; text-align: left; border: 1px solid #002F70; }
    .data-table td { padding: 8px 10px; font-size: 10.5px; border-bottom: 1px solid #e2e8f0; border-left: 1px solid #f1f5f9; border-right: 1px solid #f1f5f9; }
    .data-table tr:nth-child(even) { background: #f8fafc; }
    .status-badge { font-weight: bold; padding: 2px 6px; border-radius: 4px; font-size: 10px; display: inline-block; }
    .status-active { background: #dcfce7; color: #15803d; }
    .status-inactive { background: #fee2e2; color: #b91c1c; }
    .status-complete { color: #16a34a; font-weight: bold; }
    .status-missing { color: #dc2626; font-weight: bold; }
    .footer-table { width: 100%; margin-top: 25px; border-top: 1px solid #cbd5e1; padding-top: 10px; font-size: 10px; color: #64748b; }
</style>
</head>
<body>

<table class="header-table">
    <tr>
        <td>
            <div class="header-logo">PETRON STATION MANAGEMENT SYSTEM</div>
            <div class="header-title"><?php echo htmlspecialchars($title); ?></div>
        </td>
        <td style="text-align: right; vertical-align: top;">
            <div style="font-size: 11px; font-weight: bold; color: #002F70;"><?php echo htmlspecialchars($station_name); ?></div>
            <div style="font-size: 10px; color: #64748b;"><?php echo htmlspecialchars($now_formatted); ?></div>
        </td>
    </tr>
</table>

<table class="meta-table">
    <tr>
        <td class="meta-lbl">Station / Branch:</td>
        <td><strong><?php echo htmlspecialchars($station_name); ?></strong></td>
        <td class="meta-lbl">Generated By:</td>
        <td><strong><?php echo htmlspecialchars($admin_name); ?> (<?php echo htmlspecialchars(get_export_role_label($me['role'])); ?>)</strong></td>
    </tr>
    <tr>
        <td class="meta-lbl">Generated Date:</td>
        <td><?php echo htmlspecialchars($now_formatted); ?></td>
        <td class="meta-lbl">Total Records:</td>
        <td><strong><?php echo $record_count; ?> Employee(s)</strong></td>
    </tr>
</table>

<?php if (!$is_docs_pdf): ?>
<!-- MASTER EMPLOYEE LIST TABLE -->
<table class="data-table">
    <thead>
        <tr>
            <th style="width: 15%;">EMPLOYEE ID</th>
            <th style="width: 25%;">EMPLOYEE NAME</th>
            <th style="width: 18%;">USERNAME</th>
            <th style="width: 15%;">ROLE</th>
            <th style="width: 15%;">STATUS</th>
            <th style="width: 12%;">DATE CREATED</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($employees as $emp): 
            $emp_id    = $emp['employee_id'] ?: ('EMP-' . str_pad($emp['id'], 4, '0', STR_PAD_LEFT));
            $name      = trim($emp['full_name']) ?: $emp['username'];
            $role_name = get_export_role_label($emp['role']);
            $status    = ucfirst(strtolower(trim($emp['status'] ?: 'Active')));
            $created   = $emp['created_at'] ? date('M j, Y', strtotime($emp['created_at'])) : '—';
            $is_act    = (strtolower($status) === 'active');
        ?>
        <tr>
            <td style="font-family: monospace; font-weight: bold; color: #002F70;"><?php echo htmlspecialchars($emp_id); ?></td>
            <td><strong><?php echo htmlspecialchars($name); ?></strong></td>
            <td style="color: #475569;">@<?php echo htmlspecialchars($emp['username']); ?></td>
            <td><?php echo htmlspecialchars($role_name); ?></td>
            <td>
                <span class="status-badge <?php echo $is_act ? 'status-active' : 'status-inactive'; ?>">
                    <?php echo htmlspecialchars($status); ?>
                </span>
            </td>
            <td><?php echo htmlspecialchars($created); ?></td>
        </tr>
        <?php endforeach; ?>
        <?php if (empty($employees)): ?>
        <tr>
            <td colspan="6" style="text-align: center; padding: 20px; color: #94a3b8;">No employee records found for this station.</td>
        </tr>
        <?php endif; ?>
    </tbody>
</table>

<?php else: ?>
<!-- EMPLOYEE DOCUMENT STATUS TABLE -->
<table class="data-table">
    <thead>
        <tr>
            <th style="width: 12%;">EMP ID</th>
            <th style="width: 22%;">EMPLOYEE NAME</th>
            <th style="width: 12%;">ROLE</th>
            <th style="width: 11%;">SSS</th>
            <th style="width: 11%;">PHILHEALTH</th>
            <th style="width: 11%;">PAG-IBIG</th>
            <th style="width: 11%;">TIN</th>
            <th style="width: 10%;">VALID ID</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($employees as $emp): 
            $uid       = $emp['id'];
            $emp_id    = $emp['employee_id'] ?: ('EMP-' . str_pad($uid, 4, '0', STR_PAD_LEFT));
            $name      = trim($emp['full_name']) ?: $emp['username'];
            $role_name = get_export_role_label($emp['role']);
            
            $sss        = $docs_map[$uid]['SSS'] ?? 'Complete';
            $philhealth = $docs_map[$uid]['PhilHealth'] ?? 'Complete';
            $pagibig    = $docs_map[$uid]['Pag-IBIG'] ?? 'Complete';
            $tin        = $docs_map[$uid]['TIN'] ?? 'Complete';
            $valid_id   = $docs_map[$uid]['Valid ID'] ?? 'Complete';
        ?>
        <tr>
            <td style="font-family: monospace; font-weight: bold; color: #002F70;"><?php echo htmlspecialchars($emp_id); ?></td>
            <td><strong><?php echo htmlspecialchars($name); ?></strong></td>
            <td><?php echo htmlspecialchars($role_name); ?></td>
            <td><span class="<?php echo strtolower($sss) === 'complete' ? 'status-complete' : 'status-missing'; ?>"><?php echo htmlspecialchars($sss); ?></span></td>
            <td><span class="<?php echo strtolower($philhealth) === 'complete' ? 'status-complete' : 'status-missing'; ?>"><?php echo htmlspecialchars($philhealth); ?></span></td>
            <td><span class="<?php echo strtolower($pagibig) === 'complete' ? 'status-complete' : 'status-missing'; ?>"><?php echo htmlspecialchars($pagibig); ?></span></td>
            <td><span class="<?php echo strtolower($tin) === 'complete' ? 'status-complete' : 'status-missing'; ?>"><?php echo htmlspecialchars($tin); ?></span></td>
            <td><span class="<?php echo strtolower($valid_id) === 'complete' ? 'status-complete' : 'status-missing'; ?>"><?php echo htmlspecialchars($valid_id); ?></span></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>

<table class="footer-table">
    <tr>
        <td>Total Employees Listed: <strong><?php echo $record_count; ?></strong></td>
        <td style="text-align: right;">Generated from Petron Station Management System</td>
    </tr>
</table>

</body>
</html>
<?php
$html = ob_get_clean();

try {
    $mpdf = new \Mpdf\Mpdf([
        'mode' => 'utf-8',
        'format' => 'A4',
        'margin_left' => 12,
        'margin_right' => 12,
        'margin_top' => 12,
        'margin_bottom' => 14,
        'tempDir' => __DIR__ . '/../scratch'
    ]);
    
    $mpdf->SetTitle($title . ' - ' . $station_name);
    $mpdf->SetAuthor('Petron Station Management System');
    $mpdf->WriteHTML($html);
    
    $pdf_filename = "{$clean_station_name}_Employee_List_{$today}.pdf";
    if ($is_docs_pdf) {
        $pdf_filename = "{$clean_station_name}_Employee_Document_Status_{$today}.pdf";
    }
    
    $mpdf->Output($pdf_filename, 'I'); // Inline view in browser
} catch (\Mpdf\MpdfException $e) {
    // HTML fallback print mode if PDF engine fails
    header('Content-Type: text/html; charset=utf-8');
    echo $html;
    echo '<script>window.print();</script>';
}
exit;
