<?php
require_once __DIR__ . '/../backend/lib.php';
require_once __DIR__ . '/../public/db_connect.php';

$role = role_key(current_user()['role'] ?? 'staff');
if ($role !== 'manager') {
    header('Location: ../public/dashboard.php');
    exit;
}

try {
    $pdo = getPDO();
    $station_id = user_station_id();
    
    // Get inventory data
    $fuel_products = [];
    $stmt = $pdo->prepare("SELECT product_name, unit_cost, quantity FROM inventory_products WHERE category = 'Fuel' AND station_id = ?");
    $stmt->execute([$station_id]);
    $fuel_products = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    $merchandise_products = [];
    $stmt = $pdo->prepare("SELECT id, product_name, category, unit_cost, supplier, quantity FROM inventory_products WHERE category != 'Fuel' AND station_id = ?");
    $stmt->execute([$station_id]);
    $merchandise_products = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    // Get stock requests
    $stock_requests = [];
    $stmt = $pdo->prepare("SELECT sr.*, u.fullname as staff_name FROM stock_requests sr JOIN users u ON sr.staff_id = u.id WHERE sr.station_id = ? ORDER BY sr.created_at DESC");
    $stmt->execute([$station_id]);
    $stock_requests = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    // Generate CSV
    $filename = "inventory_export_" . date('Y-m-d_H-i-s') . ".csv";
    
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    
    $output = fopen('php://output', 'w');
    
    // Write header
    fputcsv($output, ['Inventory Report - ' . date('Y-m-d H:i:s')]);
    fputcsv($output, []);
    
    // Fuel Inventory
    fputcsv($output, ['FUEL INVENTORY']);
    fputcsv($output, ['Fuel Type', 'Current Level (L)', 'Price per Liter', 'Status']);
    
    foreach ($fuel_products as $fuel) {
        $status = $fuel['quantity'] <= 500 ? 'Out of Stock' : ($fuel['quantity'] <= 1000 ? 'Low Stock' : 'Available');
        fputcsv($output, [
            $fuel['product_name'],
            $fuel['quantity'],
            '₱' . number_format($fuel['unit_cost'], 2),
            $status
        ]);
    }
    
    fputcsv($output, []);
    
    // Merchandise Inventory
    fputcsv($output, ['MERCHANDISE INVENTORY']);
    fputcsv($output, ['Product ID', 'Name', 'Category', 'Unit Price', 'Stock Level', 'Supplier', 'Status']);
    
    foreach ($merchandise_products as $product) {
        $status = $product['quantity'] <= 10 ? 'Out of Stock' : ($product['quantity'] <= 50 ? 'Low Stock' : 'Available');
        fputcsv($output, [
            '#' . $product['id'],
            $product['product_name'],
            $product['category'],
            '₱' . number_format($product['unit_cost'], 2),
            $product['quantity'],
            $product['supplier'] ?? 'N/A',
            $status
        ]);
    }
    
    fputcsv($output, []);
    
    // Stock Requests
    fputcsv($output, ['STOCK REQUESTS']);
    fputcsv($output, ['Product Name', 'Quantity Requested', 'Staff Name', 'Date/Time', 'Status']);
    
    foreach ($stock_requests as $request) {
        fputcsv($output, [
            $request['product_name'],
            $request['quantity'],
            $request['staff_name'],
            date('M j, Y H:i', strtotime($request['created_at'])),
            ucfirst($request['status'])
        ]);
    }
    
    fputcsv($output, []);
    fputcsv($output, ['Report generated by: ' . current_user()['fullname']]);
    fputcsv($output, ['Station ID: ' . $station_id]);
    
    fclose($output);
    exit;
    
} catch (Exception $e) {
    $_SESSION['error'] = "Export failed: " . $e->getMessage();
    header('Location: inventory_manager.php');
    exit;
}
?>
