-- ==========================================================================
-- PETRON POS SYSTEM: PERMANENT DESIGNER LAYOUT BACKUP & AUTO-RESTORE
-- Database: petron_pos_db_secure
-- Generated: 2026-09-08 06:53:21
-- ==========================================================================

-- Clean existing designer data for petron_pos_db_secure
DELETE FROM phpmyadmin.pma__table_coords WHERE db_name = 'petron_pos_db_secure';
DELETE FROM phpmyadmin.pma__pdf_pages WHERE db_name = 'petron_pos_db_secure';
DELETE FROM phpmyadmin.pma__relation WHERE master_db = 'petron_pos_db_secure';

-- 1. Designer Pages
INSERT INTO phpmyadmin.pma__pdf_pages (page_nr, db_name, page_descr) VALUES (1, 'petron_pos_db_secure', 'petron_pos_db_secure') ON DUPLICATE KEY UPDATE page_descr = 'petron_pos_db_secure';
INSERT INTO phpmyadmin.pma__pdf_pages (page_nr, db_name, page_descr) VALUES (2, 'petron_pos_db_secure', '01. Master Full Schema (All 107 Tables)') ON DUPLICATE KEY UPDATE page_descr = '01. Master Full Schema (All 107 Tables)';
INSERT INTO phpmyadmin.pma__pdf_pages (page_nr, db_name, page_descr) VALUES (3, 'petron_pos_db_secure', '02. Core Organization & Users') ON DUPLICATE KEY UPDATE page_descr = '02. Core Organization & Users';
INSERT INTO phpmyadmin.pma__pdf_pages (page_nr, db_name, page_descr) VALUES (4, 'petron_pos_db_secure', '03. Fuel Management & Inventory') ON DUPLICATE KEY UPDATE page_descr = '03. Fuel Management & Inventory';
INSERT INTO phpmyadmin.pma__pdf_pages (page_nr, db_name, page_descr) VALUES (5, 'petron_pos_db_secure', '04. Merchandise & Inventory') ON DUPLICATE KEY UPDATE page_descr = '04. Merchandise & Inventory';
INSERT INTO phpmyadmin.pma__pdf_pages (page_nr, db_name, page_descr) VALUES (6, 'petron_pos_db_secure', '05. POS, Transactions & Shifts') ON DUPLICATE KEY UPDATE page_descr = '05. POS, Transactions & Shifts';
INSERT INTO phpmyadmin.pma__pdf_pages (page_nr, db_name, page_descr) VALUES (7, 'petron_pos_db_secure', '06. Services & Job Orders') ON DUPLICATE KEY UPDATE page_descr = '06. Services & Job Orders';
INSERT INTO phpmyadmin.pma__pdf_pages (page_nr, db_name, page_descr) VALUES (8, 'petron_pos_db_secure', '07. Customers & Loyalty') ON DUPLICATE KEY UPDATE page_descr = '07. Customers & Loyalty';
INSERT INTO phpmyadmin.pma__pdf_pages (page_nr, db_name, page_descr) VALUES (9, 'petron_pos_db_secure', '08. System Config & Auditing') ON DUPLICATE KEY UPDATE page_descr = '08. System Config & Auditing';

-- 2. Table Coordinates (535 entries)
INSERT INTO phpmyadmin.pma__table_coords (db_name, table_name, pdf_page_number, x, y) VALUES
  ('petron_pos_db_secure', 'stations', -1, 50, 50),
  ('petron_pos_db_secure', 'ph_regions', -1, 50, 575),
  ('petron_pos_db_secure', 'employee_documents', -1, 50, 812),
  ('petron_pos_db_secure', 'users', -1, 490, 50),
  ('petron_pos_db_secure', 'mechanics', -1, 490, 695),
  ('petron_pos_db_secure', 'login_attempts', -1, 490, 1244),
  ('petron_pos_db_secure', 'user_preferences', -1, 930, 50),
  ('petron_pos_db_secure', 'user_form_drafts', -1, 930, 359),
  ('petron_pos_db_secure', 'password_reset_tokens', -1, 930, 740),
  ('petron_pos_db_secure', 'fuel_types', -1, 1370, 50),
  ('petron_pos_db_secure', 'fuel_inventory', -1, 1370, 335),
  ('petron_pos_db_secure', 'fuel_deliveries', -1, 1370, 908),
  ('petron_pos_db_secure', 'fuel_sales_closing', -1, 1370, 1433),
  ('petron_pos_db_secure', 'fuel_pricing', -1, 1810, 50),
  ('petron_pos_db_secure', 'fuel_pumps', -1, 1810, 431),
  ('petron_pos_db_secure', 'fuel_stock_in', -1, 1810, 860),
  ('petron_pos_db_secure', 'fuel_transactions', -1, 1810, 1433),
  ('petron_pos_db_secure', 'fuel_price_log', -1, 2250, 50),
  ('petron_pos_db_secure', 'fuel_batches', -1, 2250, 551),
  ('petron_pos_db_secure', 'fuel_purchase_orders', -1, 2250, 1100),
  ('petron_pos_db_secure', 'fuel_variance_reports', -1, 2250, 1769),
  ('petron_pos_db_secure', 'fuel_price_history', -1, 2690, 50),
  ('petron_pos_db_secure', 'fuel_suppliers', -1, 2690, 575),
  ('petron_pos_db_secure', 'fuel_management_config', -1, 2690, 1028),
  ('petron_pos_db_secure', 'fuel_stock_requests', -1, 2690, 1409),
  ('petron_pos_db_secure', 'fuel_stock_request_audit', -1, 2690, 2006),
  ('petron_pos_db_secure', 'fuel_adjustments', -1, 2690, 2387),
  ('petron_pos_db_secure', 'fuel_calibration_records', -1, 2690, 3056),
  ('petron_pos_db_secure', 'fuel_config_history', -1, 2690, 3533),
  ('petron_pos_db_secure', 'fuel_status_history', -1, 2690, 3938),
  ('petron_pos_db_secure', 'products', -1, 3130, 50),
  ('petron_pos_db_secure', 'inventory_products', -1, 3130, 719),
  ('petron_pos_db_secure', 'stock_requests', -1, 3130, 1460),
  ('petron_pos_db_secure', 'pending_price_approvals', -1, 3130, 2081),
  ('petron_pos_db_secure', 'product_categories', -1, 3570, 50),
  ('petron_pos_db_secure', 'station_inventory', -1, 3570, 311),
  ('petron_pos_db_secure', 'stock_request_audit', -1, 3570, 884),
  ('petron_pos_db_secure', 'product_price_history', -1, 3570, 1289),
  ('petron_pos_db_secure', 'categories', -1, 4010, 50),
  ('petron_pos_db_secure', 'product_types', -1, 4010, 335),
  ('petron_pos_db_secure', 'merchandise_batches', -1, 4010, 572),
  ('petron_pos_db_secure', 'purchase_orders', -1, 4010, 1169),
  ('petron_pos_db_secure', 'purchase_order_items', -1, 4010, 2246),
  ('petron_pos_db_secure', 'product_config_history', -1, 4010, 2699),
  ('petron_pos_db_secure', 'suppliers', -1, 4450, 50),
  ('petron_pos_db_secure', 'merchandise_stock_in', -1, 4450, 455),
  ('petron_pos_db_secure', 'merchandise_adjustments', -1, 4450, 1148),
  ('petron_pos_db_secure', 'deliveries_oversight', -1, 4450, 1769),
  ('petron_pos_db_secure', 'inventory_logs', -1, 4450, 2990),
  ('petron_pos_db_secure', 'product_status_history', -1, 4450, 3515),
  ('petron_pos_db_secure', 'master_data_requests', -1, 4450, 3896),
  ('petron_pos_db_secure', 'merchandise_transactions', -1, 4890, 50),
  ('petron_pos_db_secure', 'shifts', -1, 4890, 2063),
  ('petron_pos_db_secure', 'merchandise_transaction_items', -1, 5330, 50),
  ('petron_pos_db_secure', 'payment_methods', -1, 5330, 503),
  ('petron_pos_db_secure', 'shift_periods', -1, 5330, 764),
  ('petron_pos_db_secure', 'merchandise_transaction_audit', -1, 5770, 50),
  ('petron_pos_db_secure', 'voided_transactions', -1, 5770, 407),
  ('petron_pos_db_secure', 'transaction_adjustments', -1, 5770, 956),
  ('petron_pos_db_secure', 'transaction_requests', -1, 5770, 1433),
  ('petron_pos_db_secure', 'payment_audit_log', -1, 5770, 2006),
  ('petron_pos_db_secure', 'labor_sessions', -1, 5770, 2435),
  ('petron_pos_db_secure', 'job_orders', -1, 6210, 50),
  ('petron_pos_db_secure', 'service_categories', -1, 6210, 1727),
  ('petron_pos_db_secure', 'job_order_parts', -1, 6650, 50),
  ('petron_pos_db_secure', 'service_rates', -1, 6650, 383),
  ('petron_pos_db_secure', 'vehicle_types', -1, 6650, 788),
  ('petron_pos_db_secure', 'job_order_service_types', -1, 7090, 50),
  ('petron_pos_db_secure', 'service_fee_history', -1, 7090, 911),
  ('petron_pos_db_secure', 'service_parts_mapping', -1, 7090, 1412),
  ('petron_pos_db_secure', 'vehicle_inspection_items', -1, 7090, 1817),
  ('petron_pos_db_secure', 'customers', -1, 7530, 50),
  ('petron_pos_db_secure', 'customer_vehicles', -1, 7530, 1631),
  ('petron_pos_db_secure', 'customer_credit_transactions', -1, 7970, 50),
  ('petron_pos_db_secure', 'customer_accounts_receivable', -1, 7970, 383),
  ('petron_pos_db_secure', 'customer_timeline', -1, 7970, 812),
  ('petron_pos_db_secure', 'customer_requests', -1, 7970, 1121),
  ('petron_pos_db_secure', 'loyalty_programs', -1, 8410, 50),
  ('petron_pos_db_secure', 'loyalty_accounts', -1, 8410, 407),
  ('petron_pos_db_secure', 'loyalty_transactions', -1, 8410, 788),
  ('petron_pos_db_secure', 'system_settings', -1, 8850, 50),
  ('petron_pos_db_secure', 'system_config', -1, 8850, 455),
  ('petron_pos_db_secure', 'system_settings_audit', -1, 8850, 788),
  ('petron_pos_db_secure', 'notifications', -1, 8850, 1121),
  ('petron_pos_db_secure', 'module_settings', -1, 9290, 50),
  ('petron_pos_db_secure', 'module_config', -1, 9290, 503),
  ('petron_pos_db_secure', 'module_config_audit', -1, 9290, 908),
  ('petron_pos_db_secure', 'module_station_config', -1, 9290, 1337),
  ('petron_pos_db_secure', 'ui_config', -1, 9290, 1646),
  ('petron_pos_db_secure', 'manager_color_config', -1, 9730, 50),
  ('petron_pos_db_secure', 'staff_color_config', -1, 9730, 383),
  ('petron_pos_db_secure', 'staff_event_types', -1, 9730, 716),
  ('petron_pos_db_secure', 'staff_calendar_events', -1, 9730, 1169),
  ('petron_pos_db_secure', 'manager_meetings', -1, 9730, 1670),
  ('petron_pos_db_secure', 'admin_compliance_deadlines', -1, 9730, 2123),
  ('petron_pos_db_secure', 'activity_logs', -1, 10170, 50),
  ('petron_pos_db_secure', 'audit_logs', -1, 10170, 407),
  ('petron_pos_db_secure', 'audit_trail', -1, 10170, 908),
  ('petron_pos_db_secure', 'integration_audit', -1, 10170, 1601),
  ('petron_pos_db_secure', 'variance_alerts', -1, 10170, 1934);
INSERT INTO phpmyadmin.pma__table_coords (db_name, table_name, pdf_page_number, x, y) VALUES
  ('petron_pos_db_secure', 'error_tracking_logs', -1, 10610, 50),
  ('petron_pos_db_secure', 'system_error_logs', -1, 10610, 431),
  ('petron_pos_db_secure', 'sys_health_report_log', -1, 10610, 812),
  ('petron_pos_db_secure', 'database_backups', -1, 10610, 1265),
  ('petron_pos_db_secure', 'restore_logs', -1, 10610, 1766),
  ('petron_pos_db_secure', 'adjustment_history', -1, 10610, 2075),
  ('petron_pos_db_secure', 'adjustment_types', -1, 10610, 2504),
  ('petron_pos_db_secure', 'stations', 0, 50, 50),
  ('petron_pos_db_secure', 'ph_regions', 0, 50, 575),
  ('petron_pos_db_secure', 'employee_documents', 0, 50, 812),
  ('petron_pos_db_secure', 'users', 0, 490, 50),
  ('petron_pos_db_secure', 'mechanics', 0, 490, 695),
  ('petron_pos_db_secure', 'login_attempts', 0, 490, 1244),
  ('petron_pos_db_secure', 'user_preferences', 0, 930, 50),
  ('petron_pos_db_secure', 'user_form_drafts', 0, 930, 359),
  ('petron_pos_db_secure', 'password_reset_tokens', 0, 930, 740),
  ('petron_pos_db_secure', 'fuel_types', 0, 1370, 50),
  ('petron_pos_db_secure', 'fuel_inventory', 0, 1370, 335),
  ('petron_pos_db_secure', 'fuel_deliveries', 0, 1370, 908),
  ('petron_pos_db_secure', 'fuel_sales_closing', 0, 1370, 1433),
  ('petron_pos_db_secure', 'fuel_pricing', 0, 1810, 50),
  ('petron_pos_db_secure', 'fuel_pumps', 0, 1810, 431),
  ('petron_pos_db_secure', 'fuel_stock_in', 0, 1810, 860),
  ('petron_pos_db_secure', 'fuel_transactions', 0, 1810, 1433),
  ('petron_pos_db_secure', 'fuel_price_log', 0, 2250, 50),
  ('petron_pos_db_secure', 'fuel_batches', 0, 2250, 551),
  ('petron_pos_db_secure', 'fuel_purchase_orders', 0, 2250, 1100),
  ('petron_pos_db_secure', 'fuel_variance_reports', 0, 2250, 1769),
  ('petron_pos_db_secure', 'fuel_price_history', 0, 2690, 50),
  ('petron_pos_db_secure', 'fuel_suppliers', 0, 2690, 575),
  ('petron_pos_db_secure', 'fuel_management_config', 0, 2690, 1028),
  ('petron_pos_db_secure', 'fuel_stock_requests', 0, 2690, 1409),
  ('petron_pos_db_secure', 'fuel_stock_request_audit', 0, 2690, 2006),
  ('petron_pos_db_secure', 'fuel_adjustments', 0, 2690, 2387),
  ('petron_pos_db_secure', 'fuel_calibration_records', 0, 2690, 3056),
  ('petron_pos_db_secure', 'fuel_config_history', 0, 2690, 3533),
  ('petron_pos_db_secure', 'fuel_status_history', 0, 2690, 3938),
  ('petron_pos_db_secure', 'products', 0, 3130, 50),
  ('petron_pos_db_secure', 'inventory_products', 0, 3130, 719),
  ('petron_pos_db_secure', 'stock_requests', 0, 3130, 1460),
  ('petron_pos_db_secure', 'pending_price_approvals', 0, 3130, 2081),
  ('petron_pos_db_secure', 'product_categories', 0, 3570, 50),
  ('petron_pos_db_secure', 'station_inventory', 0, 3570, 311),
  ('petron_pos_db_secure', 'stock_request_audit', 0, 3570, 884),
  ('petron_pos_db_secure', 'product_price_history', 0, 3570, 1289),
  ('petron_pos_db_secure', 'categories', 0, 4010, 50),
  ('petron_pos_db_secure', 'product_types', 0, 4010, 335),
  ('petron_pos_db_secure', 'merchandise_batches', 0, 4010, 572),
  ('petron_pos_db_secure', 'purchase_orders', 0, 4010, 1169),
  ('petron_pos_db_secure', 'purchase_order_items', 0, 4010, 2246),
  ('petron_pos_db_secure', 'product_config_history', 0, 4010, 2699),
  ('petron_pos_db_secure', 'suppliers', 0, 4450, 50),
  ('petron_pos_db_secure', 'merchandise_stock_in', 0, 4450, 455),
  ('petron_pos_db_secure', 'merchandise_adjustments', 0, 4450, 1148),
  ('petron_pos_db_secure', 'deliveries_oversight', 0, 4450, 1769),
  ('petron_pos_db_secure', 'inventory_logs', 0, 4450, 2990),
  ('petron_pos_db_secure', 'product_status_history', 0, 4450, 3515),
  ('petron_pos_db_secure', 'master_data_requests', 0, 4450, 3896),
  ('petron_pos_db_secure', 'merchandise_transactions', 0, 4890, 50),
  ('petron_pos_db_secure', 'shifts', 0, 4890, 2063),
  ('petron_pos_db_secure', 'merchandise_transaction_items', 0, 5330, 50),
  ('petron_pos_db_secure', 'payment_methods', 0, 5330, 503),
  ('petron_pos_db_secure', 'shift_periods', 0, 5330, 764),
  ('petron_pos_db_secure', 'merchandise_transaction_audit', 0, 5770, 50),
  ('petron_pos_db_secure', 'voided_transactions', 0, 5770, 407),
  ('petron_pos_db_secure', 'transaction_adjustments', 0, 5770, 956),
  ('petron_pos_db_secure', 'transaction_requests', 0, 5770, 1433),
  ('petron_pos_db_secure', 'payment_audit_log', 0, 5770, 2006),
  ('petron_pos_db_secure', 'labor_sessions', 0, 5770, 2435),
  ('petron_pos_db_secure', 'job_orders', 0, 6210, 50),
  ('petron_pos_db_secure', 'service_categories', 0, 6210, 1727),
  ('petron_pos_db_secure', 'job_order_parts', 0, 6650, 50),
  ('petron_pos_db_secure', 'service_rates', 0, 6650, 383),
  ('petron_pos_db_secure', 'vehicle_types', 0, 6650, 788),
  ('petron_pos_db_secure', 'job_order_service_types', 0, 7090, 50),
  ('petron_pos_db_secure', 'service_fee_history', 0, 7090, 911),
  ('petron_pos_db_secure', 'service_parts_mapping', 0, 7090, 1412),
  ('petron_pos_db_secure', 'vehicle_inspection_items', 0, 7090, 1817),
  ('petron_pos_db_secure', 'customers', 0, 7530, 50),
  ('petron_pos_db_secure', 'customer_vehicles', 0, 7530, 1631),
  ('petron_pos_db_secure', 'customer_credit_transactions', 0, 7970, 50),
  ('petron_pos_db_secure', 'customer_accounts_receivable', 0, 7970, 383),
  ('petron_pos_db_secure', 'customer_timeline', 0, 7970, 812),
  ('petron_pos_db_secure', 'customer_requests', 0, 7970, 1121),
  ('petron_pos_db_secure', 'loyalty_programs', 0, 8410, 50),
  ('petron_pos_db_secure', 'loyalty_accounts', 0, 8410, 407),
  ('petron_pos_db_secure', 'loyalty_transactions', 0, 8410, 788),
  ('petron_pos_db_secure', 'system_settings', 0, 8850, 50),
  ('petron_pos_db_secure', 'system_config', 0, 8850, 455),
  ('petron_pos_db_secure', 'system_settings_audit', 0, 8850, 788),
  ('petron_pos_db_secure', 'notifications', 0, 8850, 1121),
  ('petron_pos_db_secure', 'module_settings', 0, 9290, 50),
  ('petron_pos_db_secure', 'module_config', 0, 9290, 503),
  ('petron_pos_db_secure', 'module_config_audit', 0, 9290, 908),
  ('petron_pos_db_secure', 'module_station_config', 0, 9290, 1337),
  ('petron_pos_db_secure', 'ui_config', 0, 9290, 1646),
  ('petron_pos_db_secure', 'manager_color_config', 0, 9730, 50),
  ('petron_pos_db_secure', 'staff_color_config', 0, 9730, 383),
  ('petron_pos_db_secure', 'staff_event_types', 0, 9730, 716),
  ('petron_pos_db_secure', 'staff_calendar_events', 0, 9730, 1169);
INSERT INTO phpmyadmin.pma__table_coords (db_name, table_name, pdf_page_number, x, y) VALUES
  ('petron_pos_db_secure', 'manager_meetings', 0, 9730, 1670),
  ('petron_pos_db_secure', 'admin_compliance_deadlines', 0, 9730, 2123),
  ('petron_pos_db_secure', 'activity_logs', 0, 10170, 50),
  ('petron_pos_db_secure', 'audit_logs', 0, 10170, 407),
  ('petron_pos_db_secure', 'audit_trail', 0, 10170, 908),
  ('petron_pos_db_secure', 'integration_audit', 0, 10170, 1601),
  ('petron_pos_db_secure', 'variance_alerts', 0, 10170, 1934),
  ('petron_pos_db_secure', 'error_tracking_logs', 0, 10610, 50),
  ('petron_pos_db_secure', 'system_error_logs', 0, 10610, 431),
  ('petron_pos_db_secure', 'sys_health_report_log', 0, 10610, 812),
  ('petron_pos_db_secure', 'database_backups', 0, 10610, 1265),
  ('petron_pos_db_secure', 'restore_logs', 0, 10610, 1766),
  ('petron_pos_db_secure', 'adjustment_history', 0, 10610, 2075),
  ('petron_pos_db_secure', 'adjustment_types', 0, 10610, 2504),
  ('petron_pos_db_secure', 'stations', 1, 50, 50),
  ('petron_pos_db_secure', 'ph_regions', 1, 50, 575),
  ('petron_pos_db_secure', 'employee_documents', 1, 50, 812),
  ('petron_pos_db_secure', 'users', 1, 490, 50),
  ('petron_pos_db_secure', 'mechanics', 1, 490, 695),
  ('petron_pos_db_secure', 'login_attempts', 1, 490, 1244),
  ('petron_pos_db_secure', 'user_preferences', 1, 930, 50),
  ('petron_pos_db_secure', 'user_form_drafts', 1, 930, 359),
  ('petron_pos_db_secure', 'password_reset_tokens', 1, 930, 740),
  ('petron_pos_db_secure', 'fuel_types', 1, 1370, 50),
  ('petron_pos_db_secure', 'fuel_inventory', 1, 1370, 335),
  ('petron_pos_db_secure', 'fuel_deliveries', 1, 1370, 908),
  ('petron_pos_db_secure', 'fuel_sales_closing', 1, 1370, 1433),
  ('petron_pos_db_secure', 'fuel_pricing', 1, 1810, 50),
  ('petron_pos_db_secure', 'fuel_pumps', 1, 1810, 431),
  ('petron_pos_db_secure', 'fuel_stock_in', 1, 1810, 860),
  ('petron_pos_db_secure', 'fuel_transactions', 1, 1810, 1433),
  ('petron_pos_db_secure', 'fuel_price_log', 1, 2250, 50),
  ('petron_pos_db_secure', 'fuel_batches', 1, 2250, 551),
  ('petron_pos_db_secure', 'fuel_purchase_orders', 1, 2250, 1100),
  ('petron_pos_db_secure', 'fuel_variance_reports', 1, 2250, 1769),
  ('petron_pos_db_secure', 'fuel_price_history', 1, 2690, 50),
  ('petron_pos_db_secure', 'fuel_suppliers', 1, 2690, 575),
  ('petron_pos_db_secure', 'fuel_management_config', 1, 2690, 1028),
  ('petron_pos_db_secure', 'fuel_stock_requests', 1, 2690, 1409),
  ('petron_pos_db_secure', 'fuel_stock_request_audit', 1, 2690, 2006),
  ('petron_pos_db_secure', 'fuel_adjustments', 1, 2690, 2387),
  ('petron_pos_db_secure', 'fuel_calibration_records', 1, 2690, 3056),
  ('petron_pos_db_secure', 'fuel_config_history', 1, 2690, 3533),
  ('petron_pos_db_secure', 'fuel_status_history', 1, 2690, 3938),
  ('petron_pos_db_secure', 'products', 1, 3130, 50),
  ('petron_pos_db_secure', 'inventory_products', 1, 3130, 719),
  ('petron_pos_db_secure', 'stock_requests', 1, 3130, 1460),
  ('petron_pos_db_secure', 'pending_price_approvals', 1, 3130, 2081),
  ('petron_pos_db_secure', 'product_categories', 1, 3570, 50),
  ('petron_pos_db_secure', 'station_inventory', 1, 3570, 311),
  ('petron_pos_db_secure', 'stock_request_audit', 1, 3570, 884),
  ('petron_pos_db_secure', 'product_price_history', 1, 3570, 1289),
  ('petron_pos_db_secure', 'categories', 1, 4010, 50),
  ('petron_pos_db_secure', 'product_types', 1, 4010, 335),
  ('petron_pos_db_secure', 'merchandise_batches', 1, 4010, 572),
  ('petron_pos_db_secure', 'purchase_orders', 1, 4010, 1169),
  ('petron_pos_db_secure', 'purchase_order_items', 1, 4010, 2246),
  ('petron_pos_db_secure', 'product_config_history', 1, 4010, 2699),
  ('petron_pos_db_secure', 'suppliers', 1, 4450, 50),
  ('petron_pos_db_secure', 'merchandise_stock_in', 1, 4450, 455),
  ('petron_pos_db_secure', 'merchandise_adjustments', 1, 4450, 1148),
  ('petron_pos_db_secure', 'deliveries_oversight', 1, 4450, 1769),
  ('petron_pos_db_secure', 'inventory_logs', 1, 4450, 2990),
  ('petron_pos_db_secure', 'product_status_history', 1, 4450, 3515),
  ('petron_pos_db_secure', 'master_data_requests', 1, 4450, 3896),
  ('petron_pos_db_secure', 'merchandise_transactions', 1, 4890, 50),
  ('petron_pos_db_secure', 'shifts', 1, 4890, 2063),
  ('petron_pos_db_secure', 'merchandise_transaction_items', 1, 5330, 50),
  ('petron_pos_db_secure', 'payment_methods', 1, 5330, 503),
  ('petron_pos_db_secure', 'shift_periods', 1, 5330, 764),
  ('petron_pos_db_secure', 'merchandise_transaction_audit', 1, 5770, 50),
  ('petron_pos_db_secure', 'voided_transactions', 1, 5770, 407),
  ('petron_pos_db_secure', 'transaction_adjustments', 1, 5770, 956),
  ('petron_pos_db_secure', 'transaction_requests', 1, 5770, 1433),
  ('petron_pos_db_secure', 'payment_audit_log', 1, 5770, 2006),
  ('petron_pos_db_secure', 'labor_sessions', 1, 5770, 2435),
  ('petron_pos_db_secure', 'job_orders', 1, 6210, 50),
  ('petron_pos_db_secure', 'service_categories', 1, 6210, 1727),
  ('petron_pos_db_secure', 'job_order_parts', 1, 6650, 50),
  ('petron_pos_db_secure', 'service_rates', 1, 6650, 383),
  ('petron_pos_db_secure', 'vehicle_types', 1, 6650, 788),
  ('petron_pos_db_secure', 'job_order_service_types', 1, 7090, 50),
  ('petron_pos_db_secure', 'service_fee_history', 1, 7090, 911),
  ('petron_pos_db_secure', 'service_parts_mapping', 1, 7090, 1412),
  ('petron_pos_db_secure', 'vehicle_inspection_items', 1, 7090, 1817),
  ('petron_pos_db_secure', 'customers', 1, 7530, 50),
  ('petron_pos_db_secure', 'customer_vehicles', 1, 7530, 1631),
  ('petron_pos_db_secure', 'customer_credit_transactions', 1, 7970, 50),
  ('petron_pos_db_secure', 'customer_accounts_receivable', 1, 7970, 383),
  ('petron_pos_db_secure', 'customer_timeline', 1, 7970, 812),
  ('petron_pos_db_secure', 'customer_requests', 1, 7970, 1121),
  ('petron_pos_db_secure', 'loyalty_programs', 1, 8410, 50),
  ('petron_pos_db_secure', 'loyalty_accounts', 1, 8410, 407),
  ('petron_pos_db_secure', 'loyalty_transactions', 1, 8410, 788),
  ('petron_pos_db_secure', 'system_settings', 1, 8850, 50),
  ('petron_pos_db_secure', 'system_config', 1, 8850, 455),
  ('petron_pos_db_secure', 'system_settings_audit', 1, 8850, 788),
  ('petron_pos_db_secure', 'notifications', 1, 8850, 1121),
  ('petron_pos_db_secure', 'module_settings', 1, 9290, 50),
  ('petron_pos_db_secure', 'module_config', 1, 9290, 503);
INSERT INTO phpmyadmin.pma__table_coords (db_name, table_name, pdf_page_number, x, y) VALUES
  ('petron_pos_db_secure', 'module_config_audit', 1, 9290, 908),
  ('petron_pos_db_secure', 'module_station_config', 1, 9290, 1337),
  ('petron_pos_db_secure', 'ui_config', 1, 9290, 1646),
  ('petron_pos_db_secure', 'manager_color_config', 1, 9730, 50),
  ('petron_pos_db_secure', 'staff_color_config', 1, 9730, 383),
  ('petron_pos_db_secure', 'staff_event_types', 1, 9730, 716),
  ('petron_pos_db_secure', 'staff_calendar_events', 1, 9730, 1169),
  ('petron_pos_db_secure', 'manager_meetings', 1, 9730, 1670),
  ('petron_pos_db_secure', 'admin_compliance_deadlines', 1, 9730, 2123),
  ('petron_pos_db_secure', 'activity_logs', 1, 10170, 50),
  ('petron_pos_db_secure', 'audit_logs', 1, 10170, 407),
  ('petron_pos_db_secure', 'audit_trail', 1, 10170, 908),
  ('petron_pos_db_secure', 'integration_audit', 1, 10170, 1601),
  ('petron_pos_db_secure', 'variance_alerts', 1, 10170, 1934),
  ('petron_pos_db_secure', 'error_tracking_logs', 1, 10610, 50),
  ('petron_pos_db_secure', 'system_error_logs', 1, 10610, 431),
  ('petron_pos_db_secure', 'sys_health_report_log', 1, 10610, 812),
  ('petron_pos_db_secure', 'database_backups', 1, 10610, 1265),
  ('petron_pos_db_secure', 'restore_logs', 1, 10610, 1766),
  ('petron_pos_db_secure', 'adjustment_history', 1, 10610, 2075),
  ('petron_pos_db_secure', 'adjustment_types', 1, 10610, 2504),
  ('petron_pos_db_secure', 'stations', 2, 50, 50),
  ('petron_pos_db_secure', 'ph_regions', 2, 50, 575),
  ('petron_pos_db_secure', 'employee_documents', 2, 50, 812),
  ('petron_pos_db_secure', 'users', 2, 490, 50),
  ('petron_pos_db_secure', 'mechanics', 2, 490, 695),
  ('petron_pos_db_secure', 'login_attempts', 2, 490, 1244),
  ('petron_pos_db_secure', 'user_preferences', 2, 930, 50),
  ('petron_pos_db_secure', 'user_form_drafts', 2, 930, 359),
  ('petron_pos_db_secure', 'password_reset_tokens', 2, 930, 740),
  ('petron_pos_db_secure', 'fuel_types', 2, 1370, 50),
  ('petron_pos_db_secure', 'fuel_inventory', 2, 1370, 335),
  ('petron_pos_db_secure', 'fuel_deliveries', 2, 1370, 908),
  ('petron_pos_db_secure', 'fuel_sales_closing', 2, 1370, 1433),
  ('petron_pos_db_secure', 'fuel_pricing', 2, 1810, 50),
  ('petron_pos_db_secure', 'fuel_pumps', 2, 1810, 431),
  ('petron_pos_db_secure', 'fuel_stock_in', 2, 1810, 860),
  ('petron_pos_db_secure', 'fuel_transactions', 2, 1810, 1433),
  ('petron_pos_db_secure', 'fuel_price_log', 2, 2250, 50),
  ('petron_pos_db_secure', 'fuel_batches', 2, 2250, 551),
  ('petron_pos_db_secure', 'fuel_purchase_orders', 2, 2250, 1100),
  ('petron_pos_db_secure', 'fuel_variance_reports', 2, 2250, 1769),
  ('petron_pos_db_secure', 'fuel_price_history', 2, 2690, 50),
  ('petron_pos_db_secure', 'fuel_suppliers', 2, 2690, 575),
  ('petron_pos_db_secure', 'fuel_management_config', 2, 2690, 1028),
  ('petron_pos_db_secure', 'fuel_stock_requests', 2, 2690, 1409),
  ('petron_pos_db_secure', 'fuel_stock_request_audit', 2, 2690, 2006),
  ('petron_pos_db_secure', 'fuel_adjustments', 2, 2690, 2387),
  ('petron_pos_db_secure', 'fuel_calibration_records', 2, 2690, 3056),
  ('petron_pos_db_secure', 'fuel_config_history', 2, 2690, 3533),
  ('petron_pos_db_secure', 'fuel_status_history', 2, 2690, 3938),
  ('petron_pos_db_secure', 'products', 2, 3130, 50),
  ('petron_pos_db_secure', 'inventory_products', 2, 3130, 719),
  ('petron_pos_db_secure', 'stock_requests', 2, 3130, 1460),
  ('petron_pos_db_secure', 'pending_price_approvals', 2, 3130, 2081),
  ('petron_pos_db_secure', 'product_categories', 2, 3570, 50),
  ('petron_pos_db_secure', 'station_inventory', 2, 3570, 311),
  ('petron_pos_db_secure', 'stock_request_audit', 2, 3570, 884),
  ('petron_pos_db_secure', 'product_price_history', 2, 3570, 1289),
  ('petron_pos_db_secure', 'categories', 2, 4010, 50),
  ('petron_pos_db_secure', 'product_types', 2, 4010, 335),
  ('petron_pos_db_secure', 'merchandise_batches', 2, 4010, 572),
  ('petron_pos_db_secure', 'purchase_orders', 2, 4010, 1169),
  ('petron_pos_db_secure', 'purchase_order_items', 2, 4010, 2246),
  ('petron_pos_db_secure', 'product_config_history', 2, 4010, 2699),
  ('petron_pos_db_secure', 'suppliers', 2, 4450, 50),
  ('petron_pos_db_secure', 'merchandise_stock_in', 2, 4450, 455),
  ('petron_pos_db_secure', 'merchandise_adjustments', 2, 4450, 1148),
  ('petron_pos_db_secure', 'deliveries_oversight', 2, 4450, 1769),
  ('petron_pos_db_secure', 'inventory_logs', 2, 4450, 2990),
  ('petron_pos_db_secure', 'product_status_history', 2, 4450, 3515),
  ('petron_pos_db_secure', 'master_data_requests', 2, 4450, 3896),
  ('petron_pos_db_secure', 'merchandise_transactions', 2, 4890, 50),
  ('petron_pos_db_secure', 'shifts', 2, 4890, 2063),
  ('petron_pos_db_secure', 'merchandise_transaction_items', 2, 5330, 50),
  ('petron_pos_db_secure', 'payment_methods', 2, 5330, 503),
  ('petron_pos_db_secure', 'shift_periods', 2, 5330, 764),
  ('petron_pos_db_secure', 'merchandise_transaction_audit', 2, 5770, 50),
  ('petron_pos_db_secure', 'voided_transactions', 2, 5770, 407),
  ('petron_pos_db_secure', 'transaction_adjustments', 2, 5770, 956),
  ('petron_pos_db_secure', 'transaction_requests', 2, 5770, 1433),
  ('petron_pos_db_secure', 'payment_audit_log', 2, 5770, 2006),
  ('petron_pos_db_secure', 'labor_sessions', 2, 5770, 2435),
  ('petron_pos_db_secure', 'job_orders', 2, 6210, 50),
  ('petron_pos_db_secure', 'service_categories', 2, 6210, 1727),
  ('petron_pos_db_secure', 'job_order_parts', 2, 6650, 50),
  ('petron_pos_db_secure', 'service_rates', 2, 6650, 383),
  ('petron_pos_db_secure', 'vehicle_types', 2, 6650, 788),
  ('petron_pos_db_secure', 'job_order_service_types', 2, 7090, 50),
  ('petron_pos_db_secure', 'service_fee_history', 2, 7090, 911),
  ('petron_pos_db_secure', 'service_parts_mapping', 2, 7090, 1412),
  ('petron_pos_db_secure', 'vehicle_inspection_items', 2, 7090, 1817),
  ('petron_pos_db_secure', 'customers', 2, 7530, 50),
  ('petron_pos_db_secure', 'customer_vehicles', 2, 7530, 1631),
  ('petron_pos_db_secure', 'customer_credit_transactions', 2, 7970, 50),
  ('petron_pos_db_secure', 'customer_accounts_receivable', 2, 7970, 383),
  ('petron_pos_db_secure', 'customer_timeline', 2, 7970, 812),
  ('petron_pos_db_secure', 'customer_requests', 2, 7970, 1121),
  ('petron_pos_db_secure', 'loyalty_programs', 2, 8410, 50),
  ('petron_pos_db_secure', 'loyalty_accounts', 2, 8410, 407);
INSERT INTO phpmyadmin.pma__table_coords (db_name, table_name, pdf_page_number, x, y) VALUES
  ('petron_pos_db_secure', 'loyalty_transactions', 2, 8410, 788),
  ('petron_pos_db_secure', 'system_settings', 2, 8850, 50),
  ('petron_pos_db_secure', 'system_config', 2, 8850, 455),
  ('petron_pos_db_secure', 'system_settings_audit', 2, 8850, 788),
  ('petron_pos_db_secure', 'notifications', 2, 8850, 1121),
  ('petron_pos_db_secure', 'module_settings', 2, 9290, 50),
  ('petron_pos_db_secure', 'module_config', 2, 9290, 503),
  ('petron_pos_db_secure', 'module_config_audit', 2, 9290, 908),
  ('petron_pos_db_secure', 'module_station_config', 2, 9290, 1337),
  ('petron_pos_db_secure', 'ui_config', 2, 9290, 1646),
  ('petron_pos_db_secure', 'manager_color_config', 2, 9730, 50),
  ('petron_pos_db_secure', 'staff_color_config', 2, 9730, 383),
  ('petron_pos_db_secure', 'staff_event_types', 2, 9730, 716),
  ('petron_pos_db_secure', 'staff_calendar_events', 2, 9730, 1169),
  ('petron_pos_db_secure', 'manager_meetings', 2, 9730, 1670),
  ('petron_pos_db_secure', 'admin_compliance_deadlines', 2, 9730, 2123),
  ('petron_pos_db_secure', 'activity_logs', 2, 10170, 50),
  ('petron_pos_db_secure', 'audit_logs', 2, 10170, 407),
  ('petron_pos_db_secure', 'audit_trail', 2, 10170, 908),
  ('petron_pos_db_secure', 'integration_audit', 2, 10170, 1601),
  ('petron_pos_db_secure', 'variance_alerts', 2, 10170, 1934),
  ('petron_pos_db_secure', 'error_tracking_logs', 2, 10610, 50),
  ('petron_pos_db_secure', 'system_error_logs', 2, 10610, 431),
  ('petron_pos_db_secure', 'sys_health_report_log', 2, 10610, 812),
  ('petron_pos_db_secure', 'database_backups', 2, 10610, 1265),
  ('petron_pos_db_secure', 'restore_logs', 2, 10610, 1766),
  ('petron_pos_db_secure', 'adjustment_history', 2, 10610, 2075),
  ('petron_pos_db_secure', 'adjustment_types', 2, 10610, 2504),
  ('petron_pos_db_secure', 'stations', 3, 50, 50),
  ('petron_pos_db_secure', 'ph_regions', 3, 50, 575),
  ('petron_pos_db_secure', 'employee_documents', 3, 50, 812),
  ('petron_pos_db_secure', 'users', 3, 490, 50),
  ('petron_pos_db_secure', 'mechanics', 3, 490, 695),
  ('petron_pos_db_secure', 'login_attempts', 3, 490, 1244),
  ('petron_pos_db_secure', 'user_preferences', 3, 930, 50),
  ('petron_pos_db_secure', 'user_form_drafts', 3, 930, 359),
  ('petron_pos_db_secure', 'password_reset_tokens', 3, 930, 740),
  ('petron_pos_db_secure', 'fuel_types', 4, 50, 50),
  ('petron_pos_db_secure', 'fuel_inventory', 4, 50, 335),
  ('petron_pos_db_secure', 'fuel_deliveries', 4, 50, 908),
  ('petron_pos_db_secure', 'fuel_sales_closing', 4, 50, 1433),
  ('petron_pos_db_secure', 'fuel_pricing', 4, 490, 50),
  ('petron_pos_db_secure', 'fuel_pumps', 4, 490, 431),
  ('petron_pos_db_secure', 'fuel_stock_in', 4, 490, 860),
  ('petron_pos_db_secure', 'fuel_transactions', 4, 490, 1433),
  ('petron_pos_db_secure', 'fuel_price_log', 4, 930, 50),
  ('petron_pos_db_secure', 'fuel_batches', 4, 930, 551),
  ('petron_pos_db_secure', 'fuel_purchase_orders', 4, 930, 1100),
  ('petron_pos_db_secure', 'fuel_variance_reports', 4, 930, 1769),
  ('petron_pos_db_secure', 'fuel_price_history', 4, 1370, 50),
  ('petron_pos_db_secure', 'fuel_suppliers', 4, 1370, 575),
  ('petron_pos_db_secure', 'fuel_management_config', 4, 1370, 1028),
  ('petron_pos_db_secure', 'fuel_stock_requests', 4, 1370, 1409),
  ('petron_pos_db_secure', 'fuel_stock_request_audit', 4, 1370, 2006),
  ('petron_pos_db_secure', 'fuel_adjustments', 4, 1370, 2387),
  ('petron_pos_db_secure', 'fuel_calibration_records', 4, 1370, 3056),
  ('petron_pos_db_secure', 'fuel_config_history', 4, 1370, 3533),
  ('petron_pos_db_secure', 'fuel_status_history', 4, 1370, 3938),
  ('petron_pos_db_secure', 'products', 5, 50, 50),
  ('petron_pos_db_secure', 'inventory_products', 5, 50, 719),
  ('petron_pos_db_secure', 'stock_requests', 5, 50, 1460),
  ('petron_pos_db_secure', 'pending_price_approvals', 5, 50, 2081),
  ('petron_pos_db_secure', 'product_categories', 5, 490, 50),
  ('petron_pos_db_secure', 'station_inventory', 5, 490, 311),
  ('petron_pos_db_secure', 'stock_request_audit', 5, 490, 884),
  ('petron_pos_db_secure', 'product_price_history', 5, 490, 1289),
  ('petron_pos_db_secure', 'categories', 5, 930, 50),
  ('petron_pos_db_secure', 'product_types', 5, 930, 335),
  ('petron_pos_db_secure', 'merchandise_batches', 5, 930, 572),
  ('petron_pos_db_secure', 'purchase_orders', 5, 930, 1169),
  ('petron_pos_db_secure', 'purchase_order_items', 5, 930, 2246),
  ('petron_pos_db_secure', 'product_config_history', 5, 930, 2699),
  ('petron_pos_db_secure', 'suppliers', 5, 1370, 50),
  ('petron_pos_db_secure', 'merchandise_stock_in', 5, 1370, 455),
  ('petron_pos_db_secure', 'merchandise_adjustments', 5, 1370, 1148),
  ('petron_pos_db_secure', 'deliveries_oversight', 5, 1370, 1769),
  ('petron_pos_db_secure', 'inventory_logs', 5, 1370, 2990),
  ('petron_pos_db_secure', 'product_status_history', 5, 1370, 3515),
  ('petron_pos_db_secure', 'master_data_requests', 5, 1370, 3896),
  ('petron_pos_db_secure', 'merchandise_transactions', 6, 50, 50),
  ('petron_pos_db_secure', 'shifts', 6, 50, 2063),
  ('petron_pos_db_secure', 'merchandise_transaction_items', 6, 490, 50),
  ('petron_pos_db_secure', 'payment_methods', 6, 490, 503),
  ('petron_pos_db_secure', 'shift_periods', 6, 490, 764),
  ('petron_pos_db_secure', 'merchandise_transaction_audit', 6, 930, 50),
  ('petron_pos_db_secure', 'voided_transactions', 6, 930, 407),
  ('petron_pos_db_secure', 'transaction_adjustments', 6, 930, 956),
  ('petron_pos_db_secure', 'transaction_requests', 6, 930, 1433),
  ('petron_pos_db_secure', 'payment_audit_log', 6, 930, 2006),
  ('petron_pos_db_secure', 'labor_sessions', 6, 930, 2435),
  ('petron_pos_db_secure', 'job_orders', 7, 50, 50),
  ('petron_pos_db_secure', 'service_categories', 7, 50, 1727),
  ('petron_pos_db_secure', 'job_order_parts', 7, 490, 50),
  ('petron_pos_db_secure', 'service_rates', 7, 490, 383),
  ('petron_pos_db_secure', 'vehicle_types', 7, 490, 788),
  ('petron_pos_db_secure', 'job_order_service_types', 7, 930, 50),
  ('petron_pos_db_secure', 'service_fee_history', 7, 930, 911),
  ('petron_pos_db_secure', 'service_parts_mapping', 7, 930, 1412),
  ('petron_pos_db_secure', 'vehicle_inspection_items', 7, 930, 1817),
  ('petron_pos_db_secure', 'customers', 8, 50, 50);
INSERT INTO phpmyadmin.pma__table_coords (db_name, table_name, pdf_page_number, x, y) VALUES
  ('petron_pos_db_secure', 'customer_vehicles', 8, 50, 1631),
  ('petron_pos_db_secure', 'customer_credit_transactions', 8, 490, 50),
  ('petron_pos_db_secure', 'customer_accounts_receivable', 8, 490, 383),
  ('petron_pos_db_secure', 'customer_timeline', 8, 490, 812),
  ('petron_pos_db_secure', 'customer_requests', 8, 490, 1121),
  ('petron_pos_db_secure', 'loyalty_programs', 8, 930, 50),
  ('petron_pos_db_secure', 'loyalty_accounts', 8, 930, 407),
  ('petron_pos_db_secure', 'loyalty_transactions', 8, 930, 788),
  ('petron_pos_db_secure', 'system_settings', 9, 50, 50),
  ('petron_pos_db_secure', 'system_config', 9, 50, 455),
  ('petron_pos_db_secure', 'system_settings_audit', 9, 50, 788),
  ('petron_pos_db_secure', 'notifications', 9, 50, 1121),
  ('petron_pos_db_secure', 'module_settings', 9, 490, 50),
  ('petron_pos_db_secure', 'module_config', 9, 490, 503),
  ('petron_pos_db_secure', 'module_config_audit', 9, 490, 908),
  ('petron_pos_db_secure', 'module_station_config', 9, 490, 1337),
  ('petron_pos_db_secure', 'ui_config', 9, 490, 1646),
  ('petron_pos_db_secure', 'manager_color_config', 9, 930, 50),
  ('petron_pos_db_secure', 'staff_color_config', 9, 930, 383),
  ('petron_pos_db_secure', 'staff_event_types', 9, 930, 716),
  ('petron_pos_db_secure', 'staff_calendar_events', 9, 930, 1169),
  ('petron_pos_db_secure', 'manager_meetings', 9, 930, 1670),
  ('petron_pos_db_secure', 'admin_compliance_deadlines', 9, 930, 2123),
  ('petron_pos_db_secure', 'activity_logs', 9, 1370, 50),
  ('petron_pos_db_secure', 'audit_logs', 9, 1370, 407),
  ('petron_pos_db_secure', 'audit_trail', 9, 1370, 908),
  ('petron_pos_db_secure', 'integration_audit', 9, 1370, 1601),
  ('petron_pos_db_secure', 'variance_alerts', 9, 1370, 1934),
  ('petron_pos_db_secure', 'error_tracking_logs', 9, 1810, 50),
  ('petron_pos_db_secure', 'system_error_logs', 9, 1810, 431),
  ('petron_pos_db_secure', 'sys_health_report_log', 9, 1810, 812),
  ('petron_pos_db_secure', 'database_backups', 9, 1810, 1265),
  ('petron_pos_db_secure', 'restore_logs', 9, 1810, 1766),
  ('petron_pos_db_secure', 'adjustment_history', 9, 1810, 2075),
  ('petron_pos_db_secure', 'adjustment_types', 9, 1810, 2504);

-- 3. Internal Relations (252 entries)
INSERT IGNORE INTO phpmyadmin.pma__relation (master_db, master_table, master_field, foreign_db, foreign_table, foreign_field) VALUES
  ('petron_pos_db_secure', 'activity_logs', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'adjustment_history', 'adjustment_type_id', 'petron_pos_db_secure', 'adjustment_types', 'id'),
  ('petron_pos_db_secure', 'adjustment_history', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'adjustment_history', 'request_id', 'petron_pos_db_secure', 'stock_requests', 'id'),
  ('petron_pos_db_secure', 'adjustment_history', 'requested_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'adjustment_history', 'transaction_db_id', 'petron_pos_db_secure', 'fuel_transactions', 'id'),
  ('petron_pos_db_secure', 'admin_compliance_deadlines', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'admin_compliance_deadlines', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'audit_logs', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'audit_trail', 'manager_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'audit_trail', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'audit_trail', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'customer_accounts_receivable', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
  ('petron_pos_db_secure', 'customer_accounts_receivable', 'transaction_db_id', 'petron_pos_db_secure', 'merchandise_transactions', 'id'),
  ('petron_pos_db_secure', 'customer_credit_transactions', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
  ('petron_pos_db_secure', 'customer_credit_transactions', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'customer_requests', 'customer_record_id', 'petron_pos_db_secure', 'customers', 'id'),
  ('petron_pos_db_secure', 'customer_requests', 'requested_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'customer_requests', 'reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'customer_requests', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'customer_timeline', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'customer_timeline', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
  ('petron_pos_db_secure', 'customer_vehicles', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
  ('petron_pos_db_secure', 'customers', 'mgr_reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'customers', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'customers', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'database_backups', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'database_backups', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'deliveries_oversight', 'admin_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'deliveries_oversight', 'encoded_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'deliveries_oversight', 'manager_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'deliveries_oversight', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'employee_documents', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'error_tracking_logs', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_adjustments', 'adjustment_type_id', 'petron_pos_db_secure', 'adjustment_types', 'id'),
  ('petron_pos_db_secure', 'fuel_adjustments', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_adjustments', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
  ('petron_pos_db_secure', 'fuel_adjustments', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_adjustments', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_batches', 'delivery_id', 'petron_pos_db_secure', 'fuel_deliveries', 'id'),
  ('petron_pos_db_secure', 'fuel_batches', 'encoded_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_batches', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
  ('petron_pos_db_secure', 'fuel_batches', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_calibration_records', 'staff_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_calibration_records', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_config_history', 'fuel_inventory_id', 'petron_pos_db_secure', 'fuel_inventory', 'id'),
  ('petron_pos_db_secure', 'fuel_config_history', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_config_history', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_deliveries', 'received_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_deliveries', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_deliveries', 'verified_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_inventory', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
  ('petron_pos_db_secure', 'fuel_inventory', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_inventory', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_management_config', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_management_config', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_price_history', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_price_history', 'fuel_id', 'petron_pos_db_secure', 'fuel_inventory', 'id'),
  ('petron_pos_db_secure', 'fuel_price_history', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_price_history', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_price_log', 'changed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_price_log', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
  ('petron_pos_db_secure', 'fuel_price_log', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_pricing', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_pricing', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
  ('petron_pos_db_secure', 'fuel_pricing', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_pumps', 'calibration_updated_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_pumps', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
  ('petron_pos_db_secure', 'fuel_pumps', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_purchase_orders', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_purchase_orders', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_purchase_orders', 'delivered_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_purchase_orders', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
  ('petron_pos_db_secure', 'fuel_purchase_orders', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_purchase_orders', 'supplier_id', 'petron_pos_db_secure', 'suppliers', 'id'),
  ('petron_pos_db_secure', 'fuel_sales_closing', 'encoded_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_sales_closing', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_status_history', 'changed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_status_history', 'fuel_inventory_id', 'petron_pos_db_secure', 'fuel_inventory', 'id'),
  ('petron_pos_db_secure', 'fuel_status_history', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_stock_in', 'delivery_id', 'petron_pos_db_secure', 'fuel_deliveries', 'id'),
  ('petron_pos_db_secure', 'fuel_stock_in', 'encoded_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_stock_in', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_stock_request_audit', 'performed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_stock_request_audit', 'request_id', 'petron_pos_db_secure', 'fuel_stock_requests', 'id'),
  ('petron_pos_db_secure', 'fuel_stock_requests', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
  ('petron_pos_db_secure', 'fuel_stock_requests', 'manager_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_stock_requests', 'staff_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_stock_requests', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_suppliers', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_transactions', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
  ('petron_pos_db_secure', 'fuel_transactions', 'manager_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_transactions', 'pump_id', 'petron_pos_db_secure', 'fuel_pumps', 'id'),
  ('petron_pos_db_secure', 'fuel_transactions', 'shift_id', 'petron_pos_db_secure', 'shifts', 'id'),
  ('petron_pos_db_secure', 'fuel_transactions', 'staff_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_transactions', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'fuel_transactions', 'validated_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'fuel_types', 'category_id', 'petron_pos_db_secure', 'categories', 'id'),
  ('petron_pos_db_secure', 'fuel_variance_reports', 'pump_id', 'petron_pos_db_secure', 'fuel_pumps', 'id'),
  ('petron_pos_db_secure', 'fuel_variance_reports', 'station_id', 'petron_pos_db_secure', 'stations', 'id');
INSERT IGNORE INTO phpmyadmin.pma__relation (master_db, master_table, master_field, foreign_db, foreign_table, foreign_field) VALUES
  ('petron_pos_db_secure', 'fuel_variance_reports', 'tank_id', 'petron_pos_db_secure', 'fuel_inventory', 'id'),
  ('petron_pos_db_secure', 'integration_audit', 'changed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'inventory_logs', 'product_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
  ('petron_pos_db_secure', 'inventory_logs', 'reference_id', 'petron_pos_db_secure', 'purchase_orders', 'id'),
  ('petron_pos_db_secure', 'inventory_logs', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'inventory_logs', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'inventory_products', 'category_id', 'petron_pos_db_secure', 'categories', 'id'),
  ('petron_pos_db_secure', 'inventory_products', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'job_order_parts', 'job_order_id', 'petron_pos_db_secure', 'job_orders', 'id'),
  ('petron_pos_db_secure', 'job_order_parts', 'product_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
  ('petron_pos_db_secure', 'job_order_service_types', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'job_order_service_types', 'reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'job_order_service_types', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'job_order_service_types', 'submitted_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'job_orders', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'job_orders', 'assigned_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'job_orders', 'assigned_mechanic_id', 'petron_pos_db_secure', 'mechanics', 'id'),
  ('petron_pos_db_secure', 'job_orders', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'job_orders', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
  ('petron_pos_db_secure', 'job_orders', 'reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'job_orders', 'service_category_id', 'petron_pos_db_secure', 'service_categories', 'id'),
  ('petron_pos_db_secure', 'job_orders', 'shift_id', 'petron_pos_db_secure', 'shifts', 'id'),
  ('petron_pos_db_secure', 'job_orders', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'job_orders', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'job_orders', 'validated_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'labor_sessions', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'labor_sessions', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'login_attempts', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'loyalty_accounts', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
  ('petron_pos_db_secure', 'loyalty_accounts', 'program_id', 'petron_pos_db_secure', 'loyalty_programs', 'id'),
  ('petron_pos_db_secure', 'loyalty_transactions', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'loyalty_transactions', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
  ('petron_pos_db_secure', 'loyalty_transactions', 'loyalty_account_id', 'petron_pos_db_secure', 'loyalty_accounts', 'id'),
  ('petron_pos_db_secure', 'manager_color_config', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'manager_meetings', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'manager_meetings', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'master_data_requests', 'requested_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'master_data_requests', 'reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'master_data_requests', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'mechanics', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'merchandise_adjustments', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'merchandise_adjustments', 'product_id', 'petron_pos_db_secure', 'products', 'id'),
  ('petron_pos_db_secure', 'merchandise_adjustments', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'merchandise_batches', 'delivery_id', 'petron_pos_db_secure', 'fuel_deliveries', 'id'),
  ('petron_pos_db_secure', 'merchandise_batches', 'encoded_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'merchandise_batches', 'product_id', 'petron_pos_db_secure', 'products', 'id'),
  ('petron_pos_db_secure', 'merchandise_batches', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'merchandise_batches', 'validated_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'merchandise_stock_in', 'delivery_id', 'petron_pos_db_secure', 'fuel_deliveries', 'id'),
  ('petron_pos_db_secure', 'merchandise_stock_in', 'encoded_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'merchandise_stock_in', 'po_id', 'petron_pos_db_secure', 'purchase_orders', 'id'),
  ('petron_pos_db_secure', 'merchandise_stock_in', 'product_id', 'petron_pos_db_secure', 'products', 'id'),
  ('petron_pos_db_secure', 'merchandise_stock_in', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'merchandise_transaction_audit', 'transaction_id', 'petron_pos_db_secure', 'merchandise_transactions', 'id'),
  ('petron_pos_db_secure', 'merchandise_transaction_audit', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'merchandise_transaction_items', 'batch_id', 'petron_pos_db_secure', 'merchandise_batches', 'id'),
  ('petron_pos_db_secure', 'merchandise_transaction_items', 'product_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
  ('petron_pos_db_secure', 'merchandise_transaction_items', 'transaction_id', 'petron_pos_db_secure', 'merchandise_transactions', 'id'),
  ('petron_pos_db_secure', 'merchandise_transactions', 'credit_customer_id', 'petron_pos_db_secure', 'customers', 'id'),
  ('petron_pos_db_secure', 'merchandise_transactions', 'customer_id', 'petron_pos_db_secure', 'customers', 'id'),
  ('petron_pos_db_secure', 'merchandise_transactions', 'job_order_db_id', 'petron_pos_db_secure', 'job_orders', 'id'),
  ('petron_pos_db_secure', 'merchandise_transactions', 'job_order_id', 'petron_pos_db_secure', 'job_orders', 'id'),
  ('petron_pos_db_secure', 'merchandise_transactions', 'job_order_mechanic_id', 'petron_pos_db_secure', 'mechanics', 'id'),
  ('petron_pos_db_secure', 'merchandise_transactions', 'payment_method_id', 'petron_pos_db_secure', 'payment_methods', 'id'),
  ('petron_pos_db_secure', 'merchandise_transactions', 'shift_id', 'petron_pos_db_secure', 'shifts', 'id'),
  ('petron_pos_db_secure', 'merchandise_transactions', 'staff_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'merchandise_transactions', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'merchandise_transactions', 'validated_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'module_config', 'module_key', 'petron_pos_db_secure', 'module_settings', 'module_key'),
  ('petron_pos_db_secure', 'module_config_audit', 'changed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'module_station_config', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'notifications', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'password_reset_tokens', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'payment_audit_log', 'staff_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'payment_audit_log', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'pending_price_approvals', 'admin_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'pending_price_approvals', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
  ('petron_pos_db_secure', 'pending_price_approvals', 'manager_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'pending_price_approvals', 'product_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
  ('petron_pos_db_secure', 'pending_price_approvals', 'requested_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'pending_price_approvals', 'reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'pending_price_approvals', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'product_config_history', 'changed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'product_config_history', 'product_id', 'petron_pos_db_secure', 'products', 'id'),
  ('petron_pos_db_secure', 'product_config_history', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'product_price_history', 'approved_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'product_price_history', 'product_id', 'petron_pos_db_secure', 'products', 'id'),
  ('petron_pos_db_secure', 'product_price_history', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'product_status_history', 'changed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'product_status_history', 'product_id', 'petron_pos_db_secure', 'products', 'id'),
  ('petron_pos_db_secure', 'product_status_history', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'products', 'category_id', 'petron_pos_db_secure', 'product_categories', 'id'),
  ('petron_pos_db_secure', 'products', 'fuel_type_id', 'petron_pos_db_secure', 'fuel_types', 'id'),
  ('petron_pos_db_secure', 'products', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'products', 'top_category_id', 'petron_pos_db_secure', 'categories', 'id'),
  ('petron_pos_db_secure', 'products', 'type_id', 'petron_pos_db_secure', 'product_types', 'id'),
  ('petron_pos_db_secure', 'purchase_order_items', 'po_id', 'petron_pos_db_secure', 'purchase_orders', 'id'),
  ('petron_pos_db_secure', 'purchase_order_items', 'product_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
  ('petron_pos_db_secure', 'purchase_orders', 'admin_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'purchase_orders', 'approved_by', 'petron_pos_db_secure', 'users', 'id');
INSERT IGNORE INTO phpmyadmin.pma__relation (master_db, master_table, master_field, foreign_db, foreign_table, foreign_field) VALUES
  ('petron_pos_db_secure', 'purchase_orders', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'purchase_orders', 'request_id', 'petron_pos_db_secure', 'stock_requests', 'id'),
  ('petron_pos_db_secure', 'purchase_orders', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'purchase_orders', 'supplier_id', 'petron_pos_db_secure', 'suppliers', 'id'),
  ('petron_pos_db_secure', 'restore_logs', 'restored_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'service_fee_history', 'changed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'service_fee_history', 'service_id', 'petron_pos_db_secure', 'service_categories', 'id'),
  ('petron_pos_db_secure', 'service_parts_mapping', 'product_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
  ('petron_pos_db_secure', 'service_parts_mapping', 'service_category_id', 'petron_pos_db_secure', 'service_categories', 'id'),
  ('petron_pos_db_secure', 'service_rates', 'service_category_id', 'petron_pos_db_secure', 'service_categories', 'id'),
  ('petron_pos_db_secure', 'service_rates', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'staff_calendar_events', 'event_type_id', 'petron_pos_db_secure', 'staff_event_types', 'id'),
  ('petron_pos_db_secure', 'staff_calendar_events', 'manager_assigned_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'staff_calendar_events', 'staff_encoder_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'staff_calendar_events', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'staff_color_config', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'staff_event_types', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'staff_event_types', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'station_inventory', 'product_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
  ('petron_pos_db_secure', 'station_inventory', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'stations', 'region_id', 'petron_pos_db_secure', 'ph_regions', 'id'),
  ('petron_pos_db_secure', 'stock_request_audit', 'performed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'stock_request_audit', 'request_id', 'petron_pos_db_secure', 'stock_requests', 'id'),
  ('petron_pos_db_secure', 'stock_request_audit', 'stock_request_id', 'petron_pos_db_secure', 'stock_requests', 'id'),
  ('petron_pos_db_secure', 'stock_requests', 'item_id', 'petron_pos_db_secure', 'inventory_products', 'id'),
  ('petron_pos_db_secure', 'stock_requests', 'manager_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'stock_requests', 'staff_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'stock_requests', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'suppliers', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'sys_health_report_log', 'recorded_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'sys_health_report_log', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'system_config', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'system_error_logs', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'system_settings', 'updated_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'system_settings_audit', 'changed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'transaction_adjustments', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'transaction_requests', 'reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'transaction_requests', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'ui_config', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'user_form_drafts', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'user_form_drafts', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'user_preferences', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'users', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'variance_alerts', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'variance_alerts', 'user_id', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'vehicle_inspection_items', 'created_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'vehicle_inspection_items', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'vehicle_types', 'reviewed_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'vehicle_types', 'submitted_by', 'petron_pos_db_secure', 'users', 'id'),
  ('petron_pos_db_secure', 'voided_transactions', 'merchandise_txn_id', 'petron_pos_db_secure', 'merchandise_transactions', 'id'),
  ('petron_pos_db_secure', 'voided_transactions', 'station_id', 'petron_pos_db_secure', 'stations', 'id'),
  ('petron_pos_db_secure', 'voided_transactions', 'voided_by', 'petron_pos_db_secure', 'users', 'id');

-- 4. Visual Settings
REPLACE INTO phpmyadmin.pma__designer_settings (username, settings_data) VALUES ('root', '{\"snap_to_grid\":\"off\",\"angular_direct\":\"direct\",\"side_menu\":\"false\",\"small_big\":\"v\",\"pin_text\":\"true\",\"relation_lines\":\"true\",\"full_screen\":\"off\"}');
